### ISSUE TITLE
iasl disassembler endless loop, probably due to recent if...else if merging

### ISSUE THREAD

**Issue by RehabMan** [acpica/acpica#112]
This appears in a certain OEM DSDT, as disassembled with iasl previous to the if else merging commit:
```
        Method (CWAK, 1, NotSerialized)
        {
            ^PCI0.LPCB.EC0.WLSW ()
            ^PCI0.LPCB.EC0.WWSW ()
            ^PCI0.LPCB.EC0.RLED ()
            If (LEqual (Arg0, 0x04))
            {
                If (LNotEqual (PIDC (0x21), Ones))
                {
                    If (LEqual (^PCI0.LPCB.EIOR (One, 0x05, 0x04F4), Zero)) {}
                }
                Else
                {
                }
            }

            If (LNotEqual (PIDC (0x04), Ones))
            {
                HSWK (Arg0)
            }

            CBDM ()
        }
```

The current code gets confused and enters an endless loop, creating a rather large file until I decide to Ctrl+C to stop it:

```
        Method (CWAK, 1, NotSerialized)
        {
            ^PCI0.LPCB.EC0.WLSW ()
            ^PCI0.LPCB.EC0.WWSW ()
            ^PCI0.LPCB.EC0.RLED ()
            If ((Arg0 == 0x04))
            {
                If ((PIDC (0x21) != Ones))
                {
                    If ((^PCI0.LPCB.EIOR (One, 0x05, 0x04F4) == Zero)) {}
                }
                ElseIf ((PIDC (0x04) != Ones))
                {
                    HSWK (Arg0)
                }
            }

 ((PIDC (0x04) != Ones))
            {
                HSWK (Arg0)
            }
        }

 ((PIDC (0x04) != Ones))
        {
            HSWK (Arg0)
        }
    }

 ((PIDC (0x04) != Ones))
    {
        HSWK (Arg0)
    }
}

 ((PIDC (0x04) != Ones))
{
    HSWK (Arg0)
}
}

 ((PIDC (0x04) != Ones))
{
    HSWK (Arg0)
}
}

 ((PIDC (0x04) != Ones))
{
    HSWK (Arg0)
}
}

 ((PIDC (0x04) != Ones))
{
    HSWK (Arg0)
}
}
... and it continues ...  forever...
```

I can probably work up a small example, or provide the DSDT.aml binary, but maybe just the code above helps discover the problem.

**Comment by acpibob** [comment]
The actual binary DSDT would also help, thanks.

**Comment by acpibob** [comment]
And yes, a small example will help also. I can then fix it tomorrow before the 12/18 ACPICA release.
Thanks,
Bob

**Comment by acpibob** [comment]
Please try this patch.

diff --git a/source/components/disassembler/dmopcode.c b/source/components/disassembler/dmopcode.c
index c1e3851..723fcae 100644
--- a/source/components/disassembler/dmopcode.c
+++ b/source/components/disassembler/dmopcode.c
@@ -1119,8 +1119,8 @@ AcpiDmConvertToElseIf (
     ACPI_PARSE_OBJECT       *ElseOp;


-    IfOp = AcpiPsGetDepthNext (NULL, OriginalElseOp);
-    if (IfOp->Common.AmlOpcode != AML_IF_OP)
+    IfOp = OriginalElseOp->Common.Value.Arg;
+    if (!IfOp || (IfOp->Common.AmlOpcode != AML_IF_OP))
     {
         /* Not an Else..If sequence, cannot convert to ElseIf */

**Comment by RehabMan** [comment]
Yes, that patch appears to work...

**Comment by acpibob** [comment]
Great, thanks for your help.
Bob

**Comment by RehabMan** [comment]
Thanks for the quick action.  Didn't realize my bug report was so timely...

**Comment by acpibob** [comment]
Yes, very timely. Thanks, we appreciate your help.
I just checked in the patch, will close this thread.

**Comment by RehabMan** [comment]
There are more serious problems with this version... I'll be looking at it in detail later this afternoon (have new snow here, so will be skiing this morning).

Will post as new issue.

**Comment by acpibob** [comment]
Can you give me some idea? I am building the release right now.
