### ISSUE TITLE
iasl disassembler issue with order of External declares

### ISSUE THREAD

**Issue by RehabMan** [acpica/acpica#119]
The order in which the disassembler writes unresolved Externals and Externals from the -fe option could be improved.

Currently, these Externals are written in their own section before the other resolved Externals (from -da option and other AML files).  This exposes a problem the compiler has with order of Externals.

For example, this small example results in an error, "Name already exists in scope (FOO1)":

```
DefinitionBlock ("TEST.aml", "DSDT", 2, "TEST", "TEST", 0x000000)
{
    External(FOO1.BAR1, MethodObj)
    External(FOO1, DeviceObj)
}
```

If we reverse the order of two Externals, no error:
```
DefinitionBlock ("TEST.aml", "DSDT", 2, "TEST", "TEST", 0x000000)
{
    External(FOO1, DeviceObj)
    External(FOO1.BAR1, MethodObj)
}
```

I think what is happening here is in the case of External(FOO1.BAR1,MethodObj), FOO1 is entered with a type of unknown.  When the compiler comes across External(FOO1,DeviceObj) instead of updating the type of the existing symbol, it issues an error.

This same problem shows up quite easily in disassembly of complex files, as the externals provided with the -fe option or unresolved externals tend to be leaf nodes.  Since they appear first, the embedded parent nodes end up getting entered in the symbol table with unknown type, even though they later appear in the file as resolved symbols (because they are usually defined in DSDT or another SSDT, for example).

I've found that if the Externals are emitted in natural order, there is not a problem, as the Externals seem to be in a good order in the AcpiGbl_ExternalList.

These are the diffs (for the disassembler):

```
diff --git a/source/common/dmextern.c b/source/common/dmextern.c
index 229397f..9765d3d 100644
--- a/source/common/dmextern.c
+++ b/source/common/dmextern.c
@@ -1157,7 +1157,7 @@ AcpiDmEmitExternals (
         if ((NextExternal->Type == ACPI_TYPE_METHOD) &&
             (!(NextExternal->Flags & ACPI_EXT_RESOLVED_REFERENCE)))
         {
-            AcpiOsPrintf ("    External (%s%s",
+            AcpiOsPrintf ("    //External (%s%s",
                 NextExternal->Path,
                 AcpiDmGetObjectTypeName (NextExternal->Type));
 
@@ -1165,7 +1165,7 @@ AcpiDmEmitExternals (
                 "guessing %u arguments\n",
                 NextExternal->Value);
 
-            NextExternal->Flags |= ACPI_EXT_EXTERNAL_EMITTED;
+            //NextExternal->Flags |= ACPI_EXT_EXTERNAL_EMITTED;
         }
 
         NextExternal = NextExternal->Next;
@@ -1189,7 +1189,7 @@ AcpiDmEmitExternals (
             if (!(NextExternal->Flags & ACPI_EXT_EXTERNAL_EMITTED) &&
                 (NextExternal->Flags & ACPI_EXT_ORIGIN_FROM_FILE))
             {
-                AcpiOsPrintf ("    External (%s%s",
+                AcpiOsPrintf ("    //External (%s%s",
                     NextExternal->Path,
                     AcpiDmGetObjectTypeName (NextExternal->Type));
 
@@ -1202,7 +1202,7 @@ AcpiDmEmitExternals (
                 {
                     AcpiOsPrintf (")\n");
                 }
-                NextExternal->Flags |= ACPI_EXT_EXTERNAL_EMITTED;
+                //NextExternal->Flags |= ACPI_EXT_EXTERNAL_EMITTED;
             }
 
             NextExternal = NextExternal->Next;
@@ -1226,12 +1226,36 @@ AcpiDmEmitExternals (
 
             if (AcpiGbl_ExternalList->Type == ACPI_TYPE_METHOD)
             {
-                AcpiOsPrintf (")    // %u Arguments\n",
-                    AcpiGbl_ExternalList->Value);
+                if (!(AcpiGbl_ExternalList->Flags & ACPI_EXT_RESOLVED_REFERENCE))
+                {
+                    AcpiOsPrintf (")    // Warning: Unresolved method, "
+                        "guessing %u arguments\n",
+                        AcpiGbl_ExternalList->Value);
+                }
+                else if (AcpiGbl_ExternalList->Flags & ACPI_EXT_ORIGIN_FROM_FILE)
+                {
+                    AcpiOsPrintf (")    // Imported: %u Arguments\n",
+                        AcpiGbl_ExternalList->Value);
+                }
+                else
+                {
+                    AcpiOsPrintf (")\n");
+                }
             }
             else
             {
-                AcpiOsPrintf (")\n");
+                if (!(AcpiGbl_ExternalList->Flags & ACPI_EXT_RESOLVED_REFERENCE))
+                {
+                    AcpiOsPrintf (") // Warning: unresolved\n");
+                }
+                else if (AcpiGbl_ExternalList->Flags & ACPI_EXT_ORIGIN_FROM_FILE)
+                {
+                    AcpiOsPrintf (") // Imported\n");
+                }
+                else
+                {
+                    AcpiOsPrintf (")\n");
+                }
             }
         }
```

I left the separate sections in the output, but made them comments, and augmented the normal External output so unresolved and imported externals are identified.  I also emit a comment for non-method unresolved externals as that is probably something to look into if one was trying to find ACPI problems...

I didn't look into allowing a type of "unknown" to be overwritten by an External declaration of known type (would be a compiler change).  That may be a more desireable fix, depending on your perspective.

**Comment by gfoury** [comment]
This looks like it fixes my bug in UX305FA disassembly.

**Comment by RehabMan** [comment]
> This looks like it fixes my bug in UX305FA disassembly.

Yes... it helps quite a bit with some very common disassembly problems having to do with External declarations across DSDT/SSDTs.

**Comment by acpibob** [comment]
We are looking at this.

Could you open a bugzilla on this at:
https://bugs.acpica.org/

Thanks,
bob

**Comment by RehabMan** [comment]
Added bugzilla 1243.

**Comment by RehabMan** [comment]
This has been fixed (various related commits).
