### ISSUE TITLE
error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]

### ISSUE THREAD

**Issue by AlexMarlo** [acpica/acpica#19]
uname -a
Linux homeplanet 3.11.3-1-ARCH #1 SMP PREEMPT Wed Oct 2 01:38:48 CEST 2013 x86_64 GNU/Linux

/usr/include/features.h:327:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]  #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)     ^ cc1: all warnings being treated as errors

**Comment by acpibob** [comment]
We added a flag to the makefile for this issue:

#
# Optionally disable fortify source. This option can cause
# compile errors in toolchains where it is already defined.
#
ifneq ($(NOFORTIFY),TRUE)
OPT_CFLAGS += -D_FORTIFY_SOURCE=2
endif
