### ISSUE TITLE
Crash while disassembling some SSDT tables

### ISSUE THREAD

**Issue by marcel-apf** [acpica/acpica#20]
Hi,

My environment:
- OS: Fedora 19, 32 bit
- Hw: qemu - latest version
- iasl ver: 20130823-64 [Oct  8 2013]

When I disassembled some of the Qemu's ACPI tables like APIC or HPET using:
iasl -e DSDT -e SSDT -d HPET
I almost always received:

*** Error in `/usr/bin/iasl': double free or corruption (!prev): 0x0881bc98 ***
======= Backtrace: =========
/lib/libc.so.6[0x46205d12]
/usr/bin/iasl[0x80a5a66]
/usr/bin/iasl[0x80a2717]
/usr/bin/iasl[0x80a284b]
/usr/bin/iasl[0x805bf32]
/usr/bin/iasl[0x8072352]
/usr/bin/iasl[0x80726c1]
/usr/bin/iasl[0x80725f5]
/usr/bin/iasl[0x80491a9]
/lib/libc.so.6(__libc_start_main+0xf3)[0x461a9963]
/usr/bin/iasl[0x80491fd]
======= Memory map: ========
08047000-0810d000 r-xp 00000000 08:06 48242      /usr/bin/iasl
0810d000-0810e000 r--p 000c5000 08:06 48242      /usr/bin/iasl
0810e000-0810f000 rw-p 000c6000 08:06 48242      /usr/bin/iasl
0810f000-08113000 rw-p 00000000 00:00 0 
087f7000-08839000 rw-p 00000000 00:00 0          [heap]
4616d000-4618c000 r-xp 00000000 08:06 4415       /usr/lib/ld-2.17.so
4618c000-4618d000 r--p 0001e000 08:06 4415       /usr/lib/ld-2.17.so
4618d000-4618e000 rw-p 0001f000 08:06 4415       /usr/lib/ld-2.17.so
46190000-46348000 r-xp 00000000 08:06 4643       /usr/lib/libc-2.17.so
46348000-46349000 ---p 001b8000 08:06 4643       /usr/lib/libc-2.17.so
46349000-4634b000 r--p 001b8000 08:06 4643       /usr/lib/libc-2.17.so
4634b000-4634c000 rw-p 001ba000 08:06 4643       /usr/lib/libc-2.17.so
4634c000-4634f000 rw-p 00000000 00:00 0 
463d2000-463ed000 r-xp 00000000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
463ed000-463ee000 r--p 0001a000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
463ee000-463ef000 rw-p 0001b000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
b7741000-b7742000 rw-p 00000000 00:00 0 
b776c000-b776f000 rw-p 00000000 00:00 0 
b776f000-b7770000 r-xp 00000000 00:00 0          [vdso]
bfc6f000-bfc91000 rw-p 00000000 00:00 0          [stack]
*** Error in `/usr/bin/iasl': double free or corruption (!prev): 0x09286cd8 ***
======= Backtrace: =========
/lib/libc.so.6[0x46205d12]
/usr/bin/iasl[0x80a5a66]
/usr/bin/iasl[0x80a2717]
/usr/bin/iasl[0x80a284b]
/usr/bin/iasl[0x805bf32]
/usr/bin/iasl[0x8072352]
/usr/bin/iasl[0x80726c1]
/usr/bin/iasl[0x80725f5]
/usr/bin/iasl[0x80491a9]
/lib/libc.so.6(__libc_start_main+0xf3)[0x461a9963]
/usr/bin/iasl[0x80491fd]
======= Memory map: ========
08047000-0810d000 r-xp 00000000 08:06 48242      /usr/bin/iasl
0810d000-0810e000 r--p 000c5000 08:06 48242      /usr/bin/iasl
0810e000-0810f000 rw-p 000c6000 08:06 48242      /usr/bin/iasl
0810f000-08113000 rw-p 00000000 00:00 0 
09262000-092a4000 rw-p 00000000 00:00 0          [heap]
4616d000-4618c000 r-xp 00000000 08:06 4415       /usr/lib/ld-2.17.so
4618c000-4618d000 r--p 0001e000 08:06 4415       /usr/lib/ld-2.17.so
4618d000-4618e000 rw-p 0001f000 08:06 4415       /usr/lib/ld-2.17.so
46190000-46348000 r-xp 00000000 08:06 4643       /usr/lib/libc-2.17.so
46348000-46349000 ---p 001b8000 08:06 4643       /usr/lib/libc-2.17.so
46349000-4634b000 r--p 001b8000 08:06 4643       /usr/lib/libc-2.17.so
4634b000-4634c000 rw-p 001ba000 08:06 4643       /usr/lib/libc-2.17.so
4634c000-4634f000 rw-p 00000000 00:00 0 
463d2000-463ed000 r-xp 00000000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
463ed000-463ee000 r--p 0001a000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
463ee000-463ef000 rw-p 0001b000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
b774b000-b774c000 rw-p 00000000 00:00 0 
b7776000-b7779000 rw-p 00000000 00:00 0 
b7779000-b777a000 r-xp 00000000 00:00 0          [vdso]
bfd37000-bfd59000 rw-p 00000000 00:00 0          [stack]
*** Error in `/usr/bin/iasl': double free or corruption (!prev): 0x09587c58 ***
======= Backtrace: =========
/lib/libc.so.6[0x46205d12]
/usr/bin/iasl[0x80a5a66]
/usr/bin/iasl[0x80a2717]
/usr/bin/iasl[0x80a284b]
/usr/bin/iasl[0x805bf32]
/usr/bin/iasl[0x8072352]
/usr/bin/iasl[0x80726c1]
/usr/bin/iasl[0x80725f5]
/usr/bin/iasl[0x80491a9]
/lib/libc.so.6(__libc_start_main+0xf3)[0x461a9963]
/usr/bin/iasl[0x80491fd]
======= Memory map: ========
08047000-0810d000 r-xp 00000000 08:06 48242      /usr/bin/iasl
0810d000-0810e000 r--p 000c5000 08:06 48242      /usr/bin/iasl
0810e000-0810f000 rw-p 000c6000 08:06 48242      /usr/bin/iasl
0810f000-08113000 rw-p 00000000 00:00 0 
09563000-095a5000 rw-p 00000000 00:00 0          [heap]
4616d000-4618c000 r-xp 00000000 08:06 4415       /usr/lib/ld-2.17.so
4618c000-4618d000 r--p 0001e000 08:06 4415       /usr/lib/ld-2.17.so
4618d000-4618e000 rw-p 0001f000 08:06 4415       /usr/lib/ld-2.17.so
46190000-46348000 r-xp 00000000 08:06 4643       /usr/lib/libc-2.17.so
46348000-46349000 ---p 001b8000 08:06 4643       /usr/lib/libc-2.17.so
46349000-4634b000 r--p 001b8000 08:06 4643       /usr/lib/libc-2.17.so
4634b000-4634c000 rw-p 001ba000 08:06 4643       /usr/lib/libc-2.17.so
4634c000-4634f000 rw-p 00000000 00:00 0 
463d2000-463ed000 r-xp 00000000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
463ed000-463ee000 r--p 0001a000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
463ee000-463ef000 rw-p 0001b000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
b77af000-b77b0000 rw-p 00000000 00:00 0 
b77da000-b77dd000 rw-p 00000000 00:00 0 
b77dd000-b77de000 r-xp 00000000 00:00 0          [vdso]
bfe96000-bfeb8000 rw-p 00000000 00:00 0          [stack]
*** Error in `/usr/bin/iasl': double free or corruption (!prev): 0x096c7c98 ***
======= Backtrace: =========
/lib/libc.so.6[0x46205d12]
/usr/bin/iasl[0x80a5a66]
/usr/bin/iasl[0x80a2717]
/usr/bin/iasl[0x80a284b]
/usr/bin/iasl[0x805bf32]
/usr/bin/iasl[0x8072352]
/usr/bin/iasl[0x80726c1]
/usr/bin/iasl[0x80725f5]
/usr/bin/iasl[0x80491a9]
/lib/libc.so.6(__libc_start_main+0xf3)[0x461a9963]
/usr/bin/iasl[0x80491fd]
======= Memory map: ========
08047000-0810d000 r-xp 00000000 08:06 48242      /usr/bin/iasl
0810d000-0810e000 r--p 000c5000 08:06 48242      /usr/bin/iasl
0810e000-0810f000 rw-p 000c6000 08:06 48242      /usr/bin/iasl
0810f000-08113000 rw-p 00000000 00:00 0 
096a3000-096e5000 rw-p 00000000 00:00 0          [heap]
4616d000-4618c000 r-xp 00000000 08:06 4415       /usr/lib/ld-2.17.so
4618c000-4618d000 r--p 0001e000 08:06 4415       /usr/lib/ld-2.17.so
4618d000-4618e000 rw-p 0001f000 08:06 4415       /usr/lib/ld-2.17.so
46190000-46348000 r-xp 00000000 08:06 4643       /usr/lib/libc-2.17.so
46348000-46349000 ---p 001b8000 08:06 4643       /usr/lib/libc-2.17.so
46349000-4634b000 r--p 001b8000 08:06 4643       /usr/lib/libc-2.17.so
4634b000-4634c000 rw-p 001ba000 08:06 4643       /usr/lib/libc-2.17.so
4634c000-4634f000 rw-p 00000000 00:00 0 
463d2000-463ed000 r-xp 00000000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
463ed000-463ee000 r--p 0001a000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
463ee000-463ef000 rw-p 0001b000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
b7714000-b7715000 rw-p 00000000 00:00 0 
b773f000-b7742000 rw-p 00000000 00:00 0 
b7742000-b7743000 r-xp 00000000 00:00 0          [vdso]
bfc43000-bfc65000 rw-p 00000000 00:00 0          [stack]
qemu: terminating on signal 15 from pid 8740
main-loop: WARNING: I/O thread spun for 1000 iterations
*** Error in `/usr/bin/iasl': double free or corruption (!prev): 0x09e5c3d0 ***
======= Backtrace: =========
/lib/libc.so.6[0x46205d12]
/usr/bin/iasl[0x80a5a66]
/usr/bin/iasl[0x80a2717]
/usr/bin/iasl[0x80a284b]
/usr/bin/iasl[0x805bf32]
/usr/bin/iasl[0x8072352]
/usr/bin/iasl[0x80726c1]
/usr/bin/iasl[0x80725f5]
/usr/bin/iasl[0x80491a9]
/lib/libc.so.6(__libc_start_main+0xf3)[0x461a9963]
/usr/bin/iasl[0x80491fd]
======= Memory map: ========
08047000-0810d000 r-xp 00000000 08:06 48242      /usr/bin/iasl
0810d000-0810e000 r--p 000c5000 08:06 48242      /usr/bin/iasl
0810e000-0810f000 rw-p 000c6000 08:06 48242      /usr/bin/iasl
0810f000-08113000 rw-p 00000000 00:00 0 
09e3c000-09e7e000 rw-p 00000000 00:00 0          [heap]
4616d000-4618c000 r-xp 00000000 08:06 4415       /usr/lib/ld-2.17.so
4618c000-4618d000 r--p 0001e000 08:06 4415       /usr/lib/ld-2.17.so
4618d000-4618e000 rw-p 0001f000 08:06 4415       /usr/lib/ld-2.17.so
46190000-46348000 r-xp 00000000 08:06 4643       /usr/lib/libc-2.17.so
46348000-46349000 ---p 001b8000 08:06 4643       /usr/lib/libc-2.17.so
46349000-4634b000 r--p 001b8000 08:06 4643       /usr/lib/libc-2.17.so
4634b000-4634c000 rw-p 001ba000 08:06 4643       /usr/lib/libc-2.17.so
4634c000-4634f000 rw-p 00000000 00:00 0 
463d2000-463ed000 r-xp 00000000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
463ed000-463ee000 r--p 0001a000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
463ee000-463ef000 rw-p 0001b000 08:06 51367      /usr/lib/libgcc_s-4.8.2-20131212.so.1
b777d000-b777e000 rw-p 00000000 00:00 0 
b77a8000-b77ab000 rw-p 00000000 00:00 0 
b77ab000-b77ac000 r-xp 00000000 00:00 0          [vdso]
bfbb1000-bfbd3000 rw-p 00000000 00:00 0          [stack]
*** Error in `/usr/bin/iasl': double free or corruption (!prev): 0x0926c410 ***

Note:
iasl -d HPET works OK.

Thanks,
Marcel

**Comment by acpibob** [comment]
Is there still any issue here?

**Comment by marcel-apf** [comment]
Hi Robert,
My setup is gone now, I was using a temp machine... I'll try to ask around if anybody on QEMU devel has a matching setup.If not, I'll try to find a new one and check this issue.
Thank you,Marcel
