### ISSUE TITLE
_T_x Regression

### ISSUE THREAD

**Issue by Moorre** [acpica/acpica#205]
Hello!
Some bug encountered with losing  _T_x  Symbols.

Example:
```        
Method (GIT0, 1, NotSerialized)
        {
            Name (_T_0, Zero)
            Store (And (Arg0, 0xFFFF), _T_0)
            If (LEqual (_T_0, 0x05))
            {
                Store (GNVS (0x173E), ASB1)
            }
            Else
            {
                Store (Zero, ASB0)
            }
        }
```

And with 20170119 version the code is losing `Name (_T_0, Zero)` at the beginning, so the code reaches an error "Object doesn't exist"
Example:
```       
Method (GIT0, 1, NotSerialized)
        {
            Store (And (Arg0, 0xFFFF), _T_0)
            If (LEqual (_T_0, 0x05))
            {
                Store (GNVS (0x173E), ASB1)
            }
            Else
            {
                Store (Zero, ASB0)
            }
        }
```

Also take a look to the `5781` line with `Store (RTMP (TPMP), Store (RTNP, TPNP)` disassembled code, plz! Why it does so?
[dsdt1.aml.zip](https://github.com/acpica/acpica/files/739697/dsdt1.aml.zip)

**Comment by mirh** [comment]
Fixed by #212?

**Comment by acpibob** [comment]
Might be fixed, especially with the latest commits.

Is the original ASL code a Switch() operator?

**Comment by acpibob** [comment]
If this is fixed, we will close it.

**Comment by Moorre** [comment]
Already fixed.
