### ISSUE TITLE
asltree compile error on macOS 10.12

### ISSUE THREAD

**Issue by hydrajump** [acpica/acpica#240]
I've tried `master` and `R03_03_17` release and both produce the following error when compiling on macOS 10.12:

```
gcc -c -D_APPLE -D_GNU_SOURCE -I../../../source/include -DACPI_ASL_COMPILER -I../../../source/compiler -Iobj -std=c99 -Wall -Wbad-function-cast -Wdeclaration-after-statement -Werror -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wstrict-aliasing=0 -Wstrict-prototypes -Wswitch-default -Wpointer-arith -Wundef -Waddress -Waggregate-return -Winit-self -Winline -Wmissing-declarations -Wmissing-field-initializers -Wnested-externs -Wold-style-definition -Wno-format-nonliteral -Wredundant-decls -Wempty-body -O2 -D_FORTIFY_SOURCE=2 -o obj/asltree.o ../../../source/compiler/asltree.c
../../../source/compiler/asltree.c:298:53: error: address of array
      'Gbl_CommentState.Latest_Parse_Node->Asl.ParseOpName' will always evaluate
      to 'true' [-Werror,-Wpointer-bool-conversion]
        if (Gbl_CommentState.Latest_Parse_Node->Asl.ParseOpName)
        ~~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
1 error generated.
make[1]: *** [obj/asltree.o] Error 1
make: *** [iasl] Error 2
```

**Comment by acpibob** [comment]
What version of gcc are you using?

Code is in function TrAllocateNode:

        Gbl_CommentState.Latest_Parse_Node = Op;
        CvDbgPrint ("trallocatenode=Set latest parse node to this node.\n");
        CvDbgPrint ("           Op->Asl.ParseOpName = %s\n",
            Gbl_CommentState.Latest_Parse_Node->Asl.ParseOpName);
        CvDbgPrint ("           Op->Asl.ParseOpcode = 0x%x\n", ParseOpcode);

**Comment by SchmErik** [comment]
@hydrajump the if statement shown in the compiler error has been removed in the following commit:

https://github.com/acpica/acpica/commit/f14e1c69d7894323912f2a0798d0d4e9472bea34

In order to eliminate this error, you should make sure that you are compiling from the most recent commit on master.

**Comment by hydrajump** [comment]
@SchmErik Thank you. I must have made a mistake and not compiled against `master`. I was able to compile all the tools after cloning the repo again. Sorry for the issue ;)

**Comment by SchmErik** [comment]
@hydrajump  No problem! Just out of curiosity are you using clang or gcc? I know that your log makes it look like you're compiling using gcc but some macOS versions link gcc to clang.

**Comment by hydrajump** [comment]
@SchmErik yeah looks like clang version 8 (whatever xcode installs).
