### ISSUE TITLE
Improve infinite loop detection mechanism by adding a deterministic timeout

### ISSUE THREAD

**Issue by strangel8p** [acpica/acpica#273]
There's an issue with infinite loop detection that stops my laptop from suspending successfully. It was already reported on https://bugzilla.kernel.org/show_bug.cgi?id=156501, and the relevant pull request can be found on https://github.com/acpica/acpica/pull/185. Nonetheless, this pull request was later moved into https://github.com/acpica/acpica/pull/196 and removed indefinitely. I would appreciate if anyone can take a look at this.

**Comment by zetalog** [comment]
Here we have a solution but also a concern.

**Comment by maforonda** [comment]
Any news on this?

**Comment by acpibob** [comment]
The timeout has been implemented via the AcpiOsGetTimer interface, and will be released in the September 2017 release.
