### ISSUE TITLE
New While() loop mechanism breaks FreeBSD

### ISSUE THREAD

**Issue by juikim** [acpica/acpica#324]
Many people reported FreeBSD is broken after I merged ACPICA 20170929, e.g.,

https://lists.freebsd.org/pipermail/svn-src-head/2017-September/104683.html

I had no choice but to revert the commit back to 20170831.  Now I found the culprit was this commit:

https://github.com/acpica/acpica/commit/9605023e7e6d1f05581502766c8cf2905bcc03d9

We cannot call AcpiLoadTables() earlier than OS clock/timer initialization because of this commit.  Was this commit really necessary?  Can't you just add short AcpiOsSleep() for each iteration if you're worried that While() loop ends too quickly?

**Comment by acpibob** [comment]
What you are saying is that there is no timer available until after ACPICA has initialized?

The main purpose of the timeout is to prevent infinite loops waiting for hardware that does not respond – and thus locking up the entire ACPI subsystem.

Previously,  we used a simple loop counter, which of course did not provide a constant timeout on different machines.

I had concerns about migrating to use AcpiOsGetTimer for reasons such as these. Every OS has a different initialization sequence. From what you’ve said, I take it that the timer for AcpiOsGetTimer is available sometime later?

A couple of ideas concerning solutions:

1)      Provide an ACPICA configuration option to use either the timer or the original loop counter

2)      Implement a mechanism to fallback to the original loop counter if the timer appears unavailable.

3)      Don’t use the timer until ACPICA initialization is complete (use a loop counter).
There’s probably a few more.

Bob

**Comment by juikim** [comment]
> I take it that the timer for AcpiOsGetTimer is available sometime later?

Correct.

> A couple of ideas concerning solutions:
...

If `AcpiOsSleep()` works early (FreeBSD does), then I think we can do something like this (after reverting the commit):
```
--- source/components/dispatcher/dscontrol.c
+++ source/components/dispatcher/dscontrol.c
@@ -338,6 +338,10 @@ AcpiDsExecEndControlOp (
                 Status = AE_AML_INFINITE_LOOP;
                 break;
             }
+            else
+            {
+                AcpiOsSleep(1);
+            }
 
             /*
              * Go back and evaluate the predicate and maybe execute the loop
--- source/include/acconfig.h
+++ source/include/acconfig.h
@@ -257,7 +257,7 @@
 
 /* Maximum number of While() loops before abort */
 
-#define ACPI_MAX_LOOP_COUNT             0x000FFFFF
+#define ACPI_MAX_LOOP_COUNT             0x00007FFF
 
 
 /******************************************************************************
```

**Comment by acpibob** [comment]
Of course, you might think about bringing up the timing stuff earlier.

**Comment by juikim** [comment]
> Of course, you might think about bringing up the timing stuff earlier.

Unfortunately, it is not easy for FreeBSD.

**Comment by acpibob** [comment]
Also, the ASL Timer() operator used AcpiOsGetTimer

**Comment by juikim** [comment]
> Also, the ASL Timer() operator used AcpiOsGetTimer.

But it's rarely used.  In fact, I haven't seen any.

**Comment by zetalog** [comment]
> We cannot call AcpiLoadTables() earlier than OS clock/timer initialization because of this commit. 

This sounds a reasonable improvement. Why don't you do this first?
AcpiLoadTables() surely can invoke AML OS functionalities as it is allowed to execute not only named object creation opcodes, but execution opcodes, why will you leave AcpiOsGetTimer() non-functioning before loading the tables?

**Comment by juikim** [comment]
We have decided to use dummy timecounter for now.
