### ISSUE TITLE
compile errors on DragonFly

### ISSUE THREAD

**Issue by zrj-rimwis** [acpica/acpica#356]
We have tried compiling 5696af540 with soon to be updated gcc-8.0 and it produces the following errors when compiling on DragonFly BSD:

```
../../../source/tools/acpiexec/aetables.c: In function 'AeInitializeTableHeader':
../../../source/tools/acpiexec/aetables.c:263:5: error: 'strncpy' output truncated before terminating nul copying 8 bytes from a string of the same length [-Werror=stringop-truncation]
     strncpy (Header->OemTableId, "AcpiExec", ACPI_OEM_TABLE_ID_SIZE);
../../../source/tools/acpiexec/aetables.c:264:5: error: 'strncpy' output truncated before terminating nul copying 4 bytes from a string of the same length [-Werror=stringop-truncation]
     strncpy (Header->AslCompilerId, "INTL", ACPI_NAME_SIZE);
cc1: all warnings being treated as errors
../../../source/tools/acpinames/antables.c: In function 'AnInitializeTableHeader':
../../../source/tools/acpinames/antables.c:214:5: error: 'strncpy' output truncated before terminating nul copying 8 bytes from a string of the same length [-Werror=stringop-truncation]
     strncpy (Header->OemTableId, "AcpiName", ACPI_OEM_TABLE_ID_SIZE);
../../../source/tools/acpinames/antables.c:215:5: error: 'strncpy' output truncated before terminating nul copying 4 bytes from a string of the same length [-Werror=stringop-truncation]
     strncpy (Header->AslCompilerId, "INTL", ACPI_NAME_SIZE);
cc1: all warnings being treated as errors
../../../source/compiler/aslanalyze.c: In function 'AnCheckMethodReturnValue':
../../../source/compiler/aslanalyze.c:467:17: error: '%s' directive writing up to 32767 bytes into a region of size 32752 [-Werror=format-overflow=]
                 "Method returns [%s], %s operator requires [%s]",
                 StringBuffer, OpInfo->Name, StringBuffer2);
../../../source/compiler/aslanalyze.c:466:13: note: 'sprintf' output 41 or more bytes (assuming 65575) into a destination of size 32768
             sprintf (MsgBuffer,
                 "Method returns [%s], %s operator requires [%s]",
                 StringBuffer, OpInfo->Name, StringBuffer2);
cc1: all warnings being treated as errors
... more -Werror=format-overflow
```

To suppress -Wstringop-truncation warnings we are considering using memcpy():
memcpy (Header->OemTableId, "AcpiExec", ACPI_OEM_TABLE_ID_SIZE);
memcpy (Header->AslCompilerId, "INTL", ACPI_NAME_SIZE);

**Comment by acpibob** [comment]
Where can we get a copy of gcc 8? it looks like it is still in development.

**Comment by acpibob** [comment]
Yes, the initial bunch of these should be using memcpy, as these are not meant to be null-terminated strings.

**Comment by acpibob** [comment]
Do you have any additional problems when compiling the kernel-level code?

**Comment by zrj-rimwis** [comment]
GCC 8.0 is currently in stage-4, it is relatively easy to compile it as standalone.
Thank you for confirmation on memcpy().

Suppressing all -Wformat-overflow (enabled by -Wformat that is enabled by -Wall) would require quite a rewrite how buffer sizes are handled in tools. On DragonFly we decided to use -Wno-format-overflow -Wno-format-truncation by default based on selected CCVER.

Handling -Wno-format-overflow in generated/unix/Makefile.config would need compiler version check.
Currently we are using 20170831 (newer versions had suspicious new errors when testing predefined methods). Our acpica maintainer will try 20180209, but I do not recall any problems when compiling kernel-level code.

**Comment by SchmErik** [comment]
Just out of curiosity, what were these errors that you were getting when testing predefined methods?

**Comment by SchmErik** [comment]
I am able to compile ACPICA using GCC 8.1 and I believe we fixed errors that look like this. I'll close it. Feel free to reopen if you still see this issue.
