### ISSUE TITLE
Facing build error for ACPI CA in  VS-2015 Windows platform. 

### ISSUE THREAD

**Issue by Perry31** [acpica/acpica#361]
I'm trying to build Visual Studio solution in Visual Studio 2015. Currently I'm facing lots of build error and warnings.

I've attached migration report generated by Visual Studio 2015 when opening 2008 solution file in 2015.

Any pointers for lead is helpful to proceed further.
[Visual_2015_UpgradeLog.zip](https://github.com/acpica/acpica/files/1730251/Visual_2015_UpgradeLog.zip)

Below is the snapshot of error,
![error_visual_2015](https://user-images.githubusercontent.com/13589548/36294206-1a13657a-1305-11e8-80b9-2d9bd7b0f46b.png)

Below is the snapshot of warnings,
![warning_vs2015](https://user-images.githubusercontent.com/13589548/36294217-32308ac0-1305-11e8-93e9-cc7452ba0b13.png)

Note:
 This Stdlib.h is access from below path,
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt

**Comment by acpibob** [comment]
Sorry, we don’t build with this version of VS (at least, we don’t yet). We release the Window binaries instead.

Looking at the list of messages and warnings from your build, this shows exactly why. It is a small project unto itself to move to different versions of VC. And of course, we must be careful to support older versions of VS/VC as well.

Please feel free to make whatever changes are necessary and post them.
Thanks,
Bob

**Comment by SchmErik** [comment]
If you would like to provide VS2015 project files, please feel free to do so. Closing
