### ISSUE TITLE
RSDP decompilation failure

### ISSUE THREAD

**Issue by vit9696** [acpica/acpica#380]
Hello,

The latest iasl fails to decode a genuine RSDP table found in a Lenovo laptop. Older iasl versions seem to have no issues with this file. The returned error for running `iasl -d RSDP.aml` is as follows:
```
Could not get ACPI tables from RSDP.aml, AE_BAD_SIGNATURE
```

Here are the compiled and decompiled table (with a previous version of iasl): [RSDP.zip](https://github.com/acpica/acpica/files/1948995/RSDP.zip)

Thanks

**Comment by SchmErik** [comment]
I found the issue and I'll get changes out tomorrow. Thanks for reporting this

**Comment by vit9696** [comment]
Hi, thanks for looking at this and a quick reply. Is the fix meant to be landed in 20180427? I checked it out, and it seems to still fail with the same error message. Thanks :)

**Comment by SchmErik** [comment]
Hi, the fix was a little more complicated than I thought. I'll post a link to the pull request here when I get the solution (aiming for the end of the week).

**Comment by vit9696** [comment]
Thanks for a patch, I have just tried it and it looks like it does not particularly solve the problem with the files above. I am currently getting an infinite loop and a heavy memory leak with the changes from that pull request:
```
$ ./generate/unix/bin/iasl -d RSDP.aml 

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20180427
Copyright (c) 2000 - 2018 Intel Corporation

Input file /Users/user/Downloads/RSDP/RSDP.aml, Length 0x24 (36) bytes
ACPI:      0x0000000000000000 000000 (v00                 00000000      00000000)
ACPI:      0x0000000000000000 000000 (v00                 00000000      00000000)
ACPI:      0x0000000000000000 000000 (v00                 00000000      00000000)
ACPI:      0x0000000000000000 000000 (v00                 00000000      00000000)
ACPI:      0x0000000000000000 000000 (v00                 00000000      00000000)
ACPI:      0x0000000000000000 000000 (v00                 00000000      00000000)
...
```

**Comment by SchmErik** [comment]
Sorry about that, I've updated the pull request just now. It should be fixed.

**Comment by vit9696** [comment]
Perfect! Works fine for me now. Thanks for your hard work!
