### ISSUE TITLE
NetBSD Kernel Undefined Behavior Sanitizer: acpica reports

### ISSUE THREAD

**Issue by luserx0** [acpica/acpica#393]
Greetings,

We're working on a UB Sanitizer for the NetBSD amd64 kernel.
We've successfully booted the kernel to a shell and we are currently handling UB reports as reported on dmesg.
We have a batch of reports concerning acpica, 
they can be seen as follows:

> [   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/namespace/nsaccess.c:601:9, load of misaligned address 0xffffffff82c0554e for type 'const UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/utilities/utstring.c:198:9, load of misaligned address 0xffffffff82c09027 for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/tables/tbprint.c:148:9, load of misaligned address 0xffffffff82b08e97 for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/tables/tbprint.c:215:9, load of misaligned address 0xffffffff82c07172 for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/tables/tbprint.c:216:9, load of misaligned address 0xffffffff82b08e97 for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/tables/tbutils.c:398:13, load of misaligned address 0xffffffff82b5bdda for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/tables/tbxfload.c:187:10, load of misaligned address 0xffffffff82b5bddf for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/dispatcher/dsmthdat.c:126:9, load of misaligned address 0xffffffff82c02169 for type 'const UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/parser/psargs.c:457:9, load of misaligned address 0xffff8000439a8071 for type 'const UINT16' which requires 2 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/parser/psargs.c:466:9, load of misaligned address 0xffff8000439a80c1 for type 'const UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/parser/psargs.c:601:9, load of misaligned address 0xffff8000439a8107 for type 'const UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/namespace/nsaccess.c:601:9, load of misaligned address 0xffff8000439a8162 for type 'const UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/dispatcher/dsinit.c:254:9, load of misaligned address 0xffffffff82b5bddf for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/tables/tbxfload.c:248:15, load of misaligned address 0xffffffff82c05bbb for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/tables/tbxface.c:292:14, load of misaligned address 0xffffffff82b5bdda for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/tables/tbxface.c:394:14, load of misaligned address 0xffffffff82b080f1 for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/events/evgpeinit.c:362:5, store to misaligned address 0xffffffff855e5a53 for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/namespace/nsinit.c:515:10, load of misaligned address 0xffffffff82c05a21 for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/events/evregion.c:611:14, load of misaligned address 0xffffffff82be38cb for type 'const ACPI_NAME' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/namespace/nsinit.c:692:10, load of misaligned address 0xffffffff82b5af46 for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/utilities/utpredef.c:132:13, load of misaligned address 0xffffffff82af2187 for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rsutils.c:188:13, store to misaligned address 0xffffe4007f566c21 for type 'UINT16' which requires 2 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rsutils.c:195:13, load of misaligned address 0xffffe4007f57170e for type 'const UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rsutils.c:195:13, store to misaligned address 0xffffe4007f566ca9 for type 'UINT32' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rsaddr.c:331:22, member access within misaligned address 0xffffe4007f571722 for type 'union AML_RESOURCE' which requires 4 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rsutils.c:202:13, load of misaligned address 0xffffe4007f571742 for type 'const UINT64' which requires 8 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rsutils.c:202:13, store to misaligned address 0xffffe4007f566d09 for type 'UINT64' which requires 8 byte alignment
[   1.0000030] KUBSan: Undefined behavior in /usr/src/sys/dev/acpi/acpica/OsdHardware.c:265:17, left shift of 255 by 24 places cannot be represented in type 'int'
[   1.0565892] pckbc1 at acpi0 (KBD, PNP0303) (kbd port)KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rscalc.c:520:13, load of misaligned address 0xffffe4007fd870e9 for type 'const UINT16' which requires 2 byte alignment
[   1.0565892] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rsmisc.c:389:13, load of misaligned address 0xffffe4007fd870e9 for type 'const UINT16' which requires 2 byte alignment
[   1.0565892] piixpm0: KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rsutils.c:299:37, member access within misaligned address 0xffffe4007fbf5719 for type 'union AML_RESOURCE' which requires 4 byte alignment
[   1.0565892] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rsutils.c:250:25, member access within misaligned address 0xffffe4007fbf5719 for type 'union AML_RESOURCE' which requires 4 byte alignment
[   1.0565892] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rsutils.c:264:31, member access within misaligned address 0xffffe4007fbf5719 for type 'union AML_RESOURCE' which requires 4 byte alignment
[   1.0565892] KUBSan: Undefined behavior in /usr/src/sys/external/bsd/acpica/dist/resources/rsutils.c:263:41, member access within misaligned address 0xffffe4007fbf5719 for type 'union AML_RESOURCE' which requires 4 byte alignment

All the reports we're handling are stored on https://netbsd.org/~kamil/kubsan/
We would like to cooperate to resolve these issues.

**Comment by SchmErik** [comment]
Which version of ACPICA is in NetBsd?

**Comment by zoulasc** [comment]
acpica-unix2-20180427

**Comment by krytarowski** [comment]
http://netbsd.org/~kamil/kubsan/0005-atf-run.txt

System and kernel version 8.99.19, probably there are no changed in the HEAD version to these files since then. Branch point May 29th:

```
From cb67dba31d54bca2a4593634a3de5a27d10763d1 Mon Sep 17 00:00:00 2001
From: wiz <wiz@NetBSD.org>
Date: Tue, 29 May 2018 08:37:33 +0000
Subject: [PATCH] Remove superfluous Pp.

---
 usr.bin/cal/cal.1 | 3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)
```

**Comment by acpibob** [comment]
ACPI tables are inherently unaligned, so this type of thing is to be expected.  Is there actually a run-time problem, or can these messages be ignored?

**Comment by krytarowski** [comment]
We want to ensure correctness of the kernel code including external sources.

Misaligned code tends to crash our kernel on stricter CPUs like ARM or SPARC. ACPI is right now available for Linux, we have it on our TODO lists.

**Comment by acpibob** [comment]
Long ago, we added a compile-time macro to support processors that don't support mis-alignment via hardware. With the Itanium gone, this need has been reduced, but perhaps it is in fact coming back.

The macro is ACPI_MISALIGNMENT_NOT_SUPPORTED. It may not fully work at this time, but this was how it was originally supported.

**Comment by krytarowski** [comment]
NetBSD still runs on itanium (with some restricted set of features), however we haven't finished ACPI support there.

@luserx0 please research this macro and give it a try!

**Comment by zoulasc** [comment]
While I think it is a good practice for portable code to not do misaligned accesses, the way forward would be: 
1. Define ACPI_MISALIGNMENT_NOT_SUPPORTED, re-run the tests, fix the issues and report back (if you are willing to take patches).
2. Define a new macro ACPI_MISALIGNMENT_IGNORE or something to __attribute__((__no_sanitize__("alignment"))) and decorate the functions that need it (provided that it works, I have not tried it).

**Comment by acpibob** [comment]
I've got a couple of things that make me wonder what you are attempting:

>>The ARMv6 architecture introduced the first hardware support for unaligned accesses.  ARM11 and Cortex-A/R processors can deal with unaligned accesses in hardware, removing the need for software routines.

Directly from Oracle:

> > Does ACPICA run on SPARC processors?
> In short, no. SPARC already had a well-entrenched firmware architecture
> by the time ACPI was developed.
> 
> In Solaris, ACPI CA is only built into Intel kernels.

**Comment by krytarowski** [comment]
```
/src/sys/arch/m68k/include/
types.h | 72 #define	__NO_STRICT_ALIGNMENT
/src/sys/arch/vax/include/
types.h | 73 #define	__NO_STRICT_ALIGNMENT
/src/sys/arch/amd64/include/
types.h | 80 #define	__NO_STRICT_ALIGNMENT
/src/sys/arch/i386/include/
types.h | 105 #define	__NO_STRICT_ALIGNMENT
```

ARM is not listed there.

Example crash due to misaligned pointer.. in userland UBSan: http://gnats.netbsd.org/53261

We observe similar  panics on new ARM boards in development e.g. due to the unportable pointer to a member of a struct with __packed property.

**Comment by krytarowski** [comment]
My excollegue ported ACPI to Linux/aarch64, but I don't recall the alignment details.

Would you accept code like this to acpica:

```
#ifdef __clang__
#define NO_SANITIZE_ALIGNMENT __attribute__((no_sanitize("alignment")))
#elif __GNUC__
#define NO_SANITIZE_ALIGNMENT __attribute__((no_sanitize_undefined))
#else
#define NO_SANITIZE_ALIGNMENT
#endif
```

And tag with it appropriate functions?

**Comment by acpibob** [comment]
We already use __attribute__ in the acgcc.h compiler-specific file. However, if "no_sanitize" is not supported by earlier versions of gcc, this may be a problem.

/*
 * This macro is used to tag functions as "printf-like" because
 * some compilers (like GCC) can catch printf format string problems.
 */
#define ACPI_PRINTF_LIKE(c) __attribute__ ((__format__ (__printf__, c, c+1)))

/*
 * Some compilers complain about unused variables. Sometimes we don't want to
 * use all the variables (for example, _AcpiModuleName). This allows us
 * to tell the compiler warning in a per-variable manner that a variable
 * is unused.
 */
#define ACPI_UNUSED_VAR __attribute__ ((unused))

**Comment by acpibob** [comment]
If you want to send a patch, we can look at it.

**Comment by krytarowski** [comment]
This was implemented in GCC in 2017 and landed GCC 8.1.0. There might be a check for this version as minimum. A similar version detection can be used for clang.

https://github.com/gcc-mirror/gcc/commit/9917317aa72c629da898788ccb30e591af5b2b84

**Comment by acpibob** [comment]
We have to support GCC going back many years.

**Comment by krytarowski** [comment]
GCC version check should do the trick, @luserx0 please have a look into it.

**Comment by luserx0** [comment]
A long thread we have created. 
I will look into all the details discussed.
My opinion is that the optimal way to proceed (if the misalignment is not causing serious trouble) is to add an option to just skip the report.

I'm onto it in any case, I'll send a patch soon

**Comment by krytarowski** [comment]
Please note that there is also an issue with left shift:

> [ 1.0000030] KUBSan: Undefined behavior in /usr/src/sys/dev/acpi/acpica/OsdHardware.c:265:17, left shift of 255 by 24 places cannot be represented in type 'int'

It has to be addressed separately.

**Comment by acpibob** [comment]
OsdHardware.c is not one of our files.

**Comment by krytarowski** [comment]
After more research there do exist aarch64 boards with dummy support for misalignment issues. I had a chat with a friend of mine porting aarch64 boards to FreeBSD and due to broken misalignment support in the board, they were trapped with monthly periods of finding low-level kernel bugs.

This means that we do want this to be handled flawlessly in acpica for NetBSD/aarch64. Our ARM port for 64-bit CPUs is maturing and we already got boards with ARM's version of ACPI to get it rolling.

**Comment by SchmErik** [comment]
> After more research there do exist aarch64 boards with dummy support for misalignment issues. I had a chat with a friend of mine porting aarch64 boards to FreeBSD and due to broken misalignment support in the board, they were trapped with monthly periods of finding low-level kernel bugs.

What do you mean by dummy support?

From what you say, the issue stems from faulty boards. The fix should come from the board manufacturer. We should not be supporting broken boards

> 
> This means that we do want this to be handled flawlessly in acpica for NetBSD/aarch64. Our ARM port for 64-bit CPUs is maturing and we already got boards with ARM's version of ACPI to get it rolling.

**Comment by krytarowski** [comment]
> What do you mean by dummy support?

I mean that the ARMv8 chip vendor not implemented it.

> From what you say, the issue stems from faulty boards. The fix should come from the board manufacturer. We should not be supporting broken boards

Please let's handle this on per-case basis, instead of a-priori decision now. NetBSD ACPI is getting closer and we have got a developer dedicated to this work.

Closing as nothing more to do here right now.

**Comment by krytarowski** [comment]
> Closing as nothing more to do here right now.

Actually I don't have privileges to close it myself, please close this report.
