### ISSUE TITLE
Syntax error, unexpected PARSEOP_NAME

### ISSUE THREAD

**Issue by parkroolucas** [acpica/acpica#450]
I de-compiled `DSDT.asl` using the following command:

```sh
iasl -dl DSDT.asl
```

I then tried to recompile `DSDT.dsl` using the following command:

```sh
iasl DSDT.dsl
```

However, it gave me this error:

```sh
❯ iasl DSDT.dsl

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20180427(RM)
Copyright (c) 2000 - 2018 Intel Corporation

Compiler aborting due to parser-detected syntax error(s)
DSDT.dsl    349:     Name (SS4, One)
Error    6126 -        ^ syntax error, unexpected PARSEOP_NAME
```

I have tried with IASL 20160422 as well, but it gave me the exact same error.

Here is the line in question:

```
Name (SS4, One)
```

And the code before and after it:

```
Name (SS1, 0x00)
Name (SS2, 0x00)
Name (SS3, One)
One
Name (SS4, One)
One
OperationRegion (GNVS, SystemMemory, 0x4FBF2000, 0x0802)
```

Any help would be greatly appreciated. I am using the DSDT from a Lenovo ThinkPad P72 - I can provide more information as needed.

Thanks in advance.

**Comment by acpibob** [comment]
Did you get any warnings in the .dsl file?

This sounds like the external declaration problem

**Comment by parkroolucas** [comment]
No - the only thing I get is the one error shown above.

I've tried removing the lines that only say `One`, leaving behind this:

```
Name (SS1, 0x00)
Name (SS2, 0x00)
Name (SS3, One)
Name (SS4, One)
```

However this only causes a slew of more issues, including a whole bunch of warnings saying `Not all control paths return a value` and errors saying `Object is not accessible from this scope`.

**Comment by parkroolucas** [comment]
This is the `DSDT.dsl` file that I am trying to compile.

[DSDT.dsl.zip](https://github.com/acpica/acpica/files/2943946/DSDT.dsl.zip)

**Comment by parkroolucas** [comment]
It was my fault - commenting out the lines that said `One` does in fact work. The errors I were getting were in relation to a method I added to the code being in the wrong scope - moving it up to the root scope fixed that issue.

**Comment by pyisme** [comment]
> It was my fault - commenting out the lines that said `One` does in fact work. The errors I were getting were in relation to a method I added to the code being in the wrong scope - moving it up to the root scope fixed that issue.

I have the same issue with you. can you help me to fix it? I am a newbie

**Comment by SchmErik** [comment]
Please post the acpidump and the disassembled files.
