### ISSUE TITLE
iASL returns 0 even on errors

### ISSUE THREAD

**Issue by lcp** [acpica/acpica#476]
When compiling the firmware for Minnowboard Max, I found that my firmware didn't contain an ACPI table and OS crashed at the very beginning. After checking the build log, there is actually an error from iasl when compiling dsdt:

  Compilation failed. 1 Errors, 2 Warnings, 61 Remarks
  No AML files were generated due to compiler error(s)

I manually compiled dsdt and found that iasl always returns 0 so 'make' wasn't aware of the error and continued the other compilation.

**Comment by lcp** [comment]
[DSDT.zip](https://github.com/acpica/acpica/files/3323454/DSDT.zip)
The dsdt in question.

My acpica version is 20190509. To reproduce the bug:

  $ iasl -pDSDT.aml DSDT.iiii
  $ echo $?

I would expect an int other than 0.

**Comment by SchmErik** [comment]
Sorry about the delay. looking at this now

**Comment by SchmErik** [comment]
This pull request should solve the problem: https://github.com/acpica/acpica/pull/480

**Comment by lcp** [comment]
The patch works for me.

**Comment by SchmErik** [comment]
this has been fixed. closing..
