### ISSUE TITLE
Illegal forward reference breaks compilation

### ISSUE THREAD

**Issue by vit9696** [acpica/acpica#533]
Hello,

After the addition of illegal forward references detection (https://github.com/acpica/acpica/commit/e855bcebcde00d23e065a1547595a785fe069d45) several previously compilable OEM ACPI tables started to bail with error.

I attach a [DSDT sample](https://github.com/acpica/acpica/files/4010165/DSDT.aml.zip) that illustrates the problem:

```
$ iasl -d DSDT.aml
$ iasl DSDT.dsl
...
DSDT.dsl   3130:                     Field (LPCR, AnyAcc, NoLock, Preserve)
Error    6142 -                           Illegal forward reference ^  (LPCR)
...
```

The lines mentioned are:
```
                    OperationRegion (^LPCR, SystemMemory, 0xFED1F404, 0x04)
                    Field (LPCR, AnyAcc, NoLock, Preserve)
                    {
                        HPTS,   2, 
                            ,   5, 
                        HPTE,   1, 
                        Offset (0x04)
                    }
```

From what I understand the compiler suggests to replace `^LPCR` with `LPCR`. I am not an expert in ACPI, but my initial thought was that these statements were equivalent for what it matters here. Please correct me, if I am wrong.

Compiling this sample with the warning disabled produces the identical DSDT except the timestamp in the header:
```
iasl -vw 6142 DSDT.dsl
```

If the diagnostic is actually correct and this is mistake, I will still request for this message to be marked as warning, not an error, as we do not expect a newer compiler to break on previously working samples. Thanks.

**Comment by SchmErik** [comment]
@vit9696 please try https://github.com/acpica/acpica/pull/534

**Comment by vit9696** [comment]
@SchmErik thanks for the fix, works correctly now.

**Comment by SchmErik** [comment]
Thanks. @acpibob please merge #534

**Comment by acpibob** [comment]
Closing.
