### ISSUE TITLE
PCC is not a defined Register() type?

### ISSUE THREAD

**Issue by ahs3** [acpica/acpica#563]
Using the latest upstream as of 2020-02-25, there seems to be something very wrong with the Register() parsing code.  This ASL does not compile:

DefinitionBlock ("", "DSDT", 2, "REDHAT", "PCCPARSE", 0x00000004)
{
     Name (FRED, Package ()
     { ResourceTemplate () { Register (PCC, 0x20, 0x00, 0x0, ,) } } )
}

These are the error messages I get:

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20200214
Copyright (c) 2000 - 2020 Intel Corporation

Compiler aborting due to parser-detected syntax error(s)
Unknown resource descriptor type [ERRORNODE]
small.asl      7:      { ResourceTemplate () { Register (PCC, 0x20, 0x00, 0x0, ,) } } )
Error    6126 -  syntax error, unexpected PARSEOP_NAMESEG ^ 

Input file:    small.asl - Compilation aborted due to parser-detected syntax error(s)

Compilation failed. 1 Errors, 0 Warnings, 0 Remarks
No AML files were generated due to syntax error(s)

The spacing is a bit off, but it points to PCC in the Register() declaration.  I believe this used to work so is this a regression or is a new rule being enforced somewhere?  Best I can tell, this is perfectly valid ASL.

I'll keep digging into it, too.

**Comment by SchmErik** [comment]
Try using PlatformCommChannel instead

**Comment by ahs3** [comment]
D'oh.  Right.  That does the trick.  I'd forgotten this had changed; the 6.3 spec still says "PCC".

This is with much older ASL files, too.

Thanks, Erik!

**Comment by SchmErik** [comment]
@ahs3 this change slipped from the cracks it was changed from PCC to PlatformCommChannel and back to PCC again. I'll submit pull request fix to PlatformCommChannel to PCC instead.

**Comment by ahs3** [comment]
Oh, man, I really lost track of this, then.  I recall the first change, but not changing it back.

*shrug*

Okay, I know what to patch in the meantime.

Thanks again.

**Comment by SchmErik** [comment]
Here's the fix: https://github.com/acpica/acpica/pull/565

I've tested it locally but let me know if this doesn't work for you

**Comment by SchmErik** [comment]
I'm going to assume this is resolved. I'll close this but please reopen if needed.
