### ISSUE TITLE
typo in WSMT expansion

### ISSUE THREAD

**Issue by lersek** [acpica/acpica#573]
Commit 4f12387029c6 (for #223) introduced five instances of the following string, expanding the WSMT signature: `Windows SMM Security Migrations Table`.

This string has a typo. `Migrations` should be replaced with `Mitigations`. The full table name is `Windows SMM Security Mitigations Table`, according to:

https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/acpi-system-description-tables#windows-smm-security-mitigations-table-wsmt

Thanks.

**Comment by SchmErik** [comment]
Thanks, fix available at #574

**Comment by lersek** [comment]
Fixed in commit 764d18c5a839 ("WSMT: Fix typo, no functional change", 2020-03-23), thank you All!
