### ISSUE TITLE
possible overflow being caught by GCC

### ISSUE THREAD

**Issue by ahs3** [acpica/acpica#576]
In GCC 10, I need to use the following patch to get iASL to compile:
```diff --git a/source/components/utilities/utresrc.c b/source/components/utilities/utresrc.c
index 56d9abf1c..af3f0b019 100644
--- a/source/components/utilities/utresrc.c
+++ b/source/components/utilities/utresrc.c
@@ -648,7 +648,7 @@ AcpiUtGetResourceLength (
     {
         /* Large Resource type -- bytes 1-2 contain the 16-bit length */
 
-        ACPI_MOVE_16_TO_16 (&ResourceLength, ACPI_ADD_PTR (UINT8, Aml, 1));
+        ACPI_MOVE_16_TO_16 (&ResourceLength, ACPI_ADD_PTR (UINT8, Aml, 0));
 
     }
     else
```
Without this, GCC complains I'll overflow EndTag (which appears to be correct).

I made this change and then ran it over ~1800 ASL files and it did not change results.  Could someone else please check if it's safe, too?  My fear is that there is someplace else in iASL that is relying on this to overflow inadvertently, even though I have not found such a place yet.

Thanks.

**Comment by SchmErik** [comment]
which version of gcc 10 are you using?

I don't have this issue and I'm using the following:
`
gcc (GCC) 10.0.1 20200216 (Red Hat 10.0.1-0.8)
`

**Comment by ahs3** [comment]
gcc (GCC) 10.0.1 20200311 (Red Hat 10.0.1-0.9)

on Fedora 33 (rawhide) on s390, if that helps.  So kinda out there, but not too far.

**Comment by ahs3** [comment]
Argh. I cannot reproduce this now.  I was running multiple experiments with big-endian support and best I can tell I crossed the streams.  Using clean versions of upstream source, this issue no longer exists.  Sorry about the noise :(.

**Comment by acpibob** [comment]
That’s ok.
Thanks,
Bob
