### ISSUE TITLE
error: "_FORTIFY_SOURCE" redefined [-Werror]

### ISSUE THREAD

**Issue by Yukariin** [acpica/acpica#59]
Hi!
I tried build latest version of iasl (20141107) and get this error.
Change `OPT_CFLAGS += -O2 -D_FORTIFY_SOURCE=2` to `OPT_CFLAGS += -O2` in `generate/unix/Makefile.config` fixed this for me.

Thanks.

**Comment by acpibob** [comment]
is this still a problem?

**Comment by acpibob** [comment]
We added a flag to the makefile:

#
# Optionally disable fortify source. This option can cause
# compile errors in toolchains where it is already defined.
#
ifneq ($(NOFORTIFY),TRUE)
OPT_CFLAGS += -D_FORTIFY_SOURCE=2
endif
