### ISSUE TITLE
acpinamese.exe  not working with latest build

### ISSUE THREAD

**Issue by shaopy** [acpica/acpica#598]
Follow below steps to try get all namespace, but found that acpinamese.exe  not working with latest build:

         1. acpidump.exe -b        //dump all acpi tables saved as *.dat files
         2. acpinames.exe *.dat > namespace.txt //parse all tables, build the whole ACPI namespace
![Snipaste_2020-04-27_14-55-54](https://user-images.githubusercontent.com/7878575/80342730-3e9ae800-8897-11ea-8f0a-a0c861962def.png)

**Comment by acpibob** [comment]
You might try just loading the dsdt.dat file. Also, you should be able to load the namespace via the acpiexec utility, then use the 'namespace' command to dump the namespace.

**Comment by acpibob** [comment]
Is this under Windows, or some other OS?

**Comment by shaopy** [comment]
this is under Windows OS but i use old build (iasl-win-20180629), it can load all SSDT and DSDT tables,  it supports  wildcard operator in old build but failed  with TOT.

only load DSDT will not work, either

![image](https://user-images.githubusercontent.com/7878575/80447331-b75b7c00-894b-11ea-83e5-f0594eb0adb4.png)

**Comment by shaopy** [comment]
regarding to load the namespace via the acpiexec utility, then use the 'namespace' command to dump the namespace, how I can save the namespace output to a file after hit “namespace” ?

**Comment by SchmErik** [comment]
an easy way to do this is to use the batch mode execution by supplying it the -b flag and the command that you want to execute. The -b flag will execute the command that you gave it and terminate acpiexec. You can capture the output by redirecting stdout to a file. In your case, this would be acpiexec -b"n" [Aml files] > namespace.txt

**Comment by shaopy** [comment]
Great, " acpiexec -b"n" *.dat > namespace.txt"  command  works .

roll back to acpinames.exe problem: with latest build,   acpinames.exe *.dat can **NOT** dump  all namespaces  within  DAT files, but old build  (20180629) can do this well

by debug, found that when main be called, argc=2 but not 14 . argv[1]=*.dat.
AcGetAllTablesFromFile call failed in this case.
![image](https://user-images.githubusercontent.com/7878575/80561148-1a194a00-8a16-11ea-9971-f51ff56d5748.png)


with old  build,  argc=14,  and argv [1~13] with correct DAT file name

![image](https://user-images.githubusercontent.com/7878575/80561444-176b2480-8a17-11ea-8a50-d78598c725f8.png)

**Comment by acpibob** [comment]
Just redirect the output to a file, such as “acpinames dsdt.dat > dsdt.txt”

**Comment by acpibob** [comment]
Yes, wildcards are broken on MSVC 2017. It may be a result of using VC 2017 to convert the project file from MSVC V9. Need to add “setargv.obj” to the default link sequence.

**Comment by acpibob** [comment]
Like this:
On Linker/input window, setargv.obj:

kernel32.lib;setargv.obj;advapi32.lib;%(AdditionalDependencies)

From: Moore, Robert
Sent: Wednesday, April 29, 2020 7:32 AM
To: acpica/acpica <reply@reply.github.com>; acpica/acpica <acpica@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [acpica/acpica] acpinamese.exe not working with latest build (#598)

Yes, wildcards are broken on MSVC 2017. It may be a result of using VC 2017 to convert the project file from MSVC V9. Need to add “setargv.obj” to the default link sequence.

**Comment by shaopy** [comment]
Yes, with  setargv.obj added into lib, the wildcard can work now. thanks

**Comment by SchmErik** [comment]
we have deprecated the acpinames utility. please use acpiexec to dump the namespace instead. Closing
