### ISSUE TITLE
acpinames.exe come across exeception and  can't proceed to dump entire namespaces

### ISSUE THREAD

**Issue by shaopy** [acpica/acpica#601]
with latest acpinames.exe, it can only load tables, but can't dump entire  namespaces.

always come across below  expceptions  and can't proceeed

![image](https://user-images.githubusercontent.com/7878575/81031019-67396800-8ebd-11ea-86b7-162bfe60a8a6.png)

![image](https://user-images.githubusercontent.com/7878575/81031060-8a641780-8ebd-11ea-8dc5-1f19c835fc21.png)

**Comment by SchmErik** [comment]
we are no longer supporting acpinames utility and it will be removed in the very near future. Please use acpiexec instead. You can dump the namespace by typing "n"

**Comment by SchmErik** [comment]
we no longer maintain this utility and has been removed in the most recent acpica release. Closing
