### ISSUE TITLE
Missing man pages in acpica documentation.

### ISSUE THREAD

**Issue by thx1111** [acpica/acpica#62]
I know there exists at least a man page for acpidump, "COPYRIGHT (c) 2013, Intel Corporation." which is included with the Linux kernel source for a similar version of acpidump.  This man page in particular, and the man pages for all the other acpica binaries, seem to be missing from this source.

Do these other man pages exist somewhere?
Would you please include at least the acpidump man page here?
Would you please provide man pages for the other binaries?

**Comment by acpibob** [comment]
Since the man pages are at least somewhat OS-dependent, ACPICA does not create or maintain them. I suggest you bring this up on the Linux-acpi mailing list:

linux-acpi@vger.kernel.org

Also, the actual ACPICA documentation is here:

https://www.acpica.org/documentation
