### ISSUE TITLE
compiler optimization issue

### ISSUE THREAD

**Issue by ElyesH** [acpica/acpica#631]
I have 4 files (see attached) that are supposed to provide the same binary, but I didn't got the same md5sum:
iasl testbin/dsdt-new.asl --> e2b1a50ba22263e875b020cc3cb9ca6e  testbin/dsdt.aml
iasl testbin/dsdt-new.dsl --> 0e4117e2cd14f165da36c851cb9f689e  testbin/dsdt-new.aml
iasl testbin/dsdt-old.asl --> 5666bb56269051f792586794dc75b645  testbin/dsdt.aml
iasl testbin/dsdt-old.dsl --> 0e4117e2cd14f165da36c851cb9f689e  testbin/dsdt-old.aml

looks like the compiler did not the same optimization for "Store (Or(ShiftLeft (Arg0, 4), 0xf), ^^DSPC.BRTC)" and "^^DSPC.BRTC = ((Arg0 << 0x04) | 0x0F)"

[compiler-issue.zip](https://github.com/acpica/acpica/files/5213060/compiler-issue.zip)

**Comment by acpibob** [comment]
Does the issue still happen if you disable optimization on the compiler command line? (-oa)

**Comment by acpibob** [comment]
Here's what I think is going on. Yes, the optimization is different between the two statements. From the listing file (-l compiler option):

      18:              Store (Or(ShiftLeft (Arg0, 4), 0xf), ^^DSPC.BRTC)
0000003F:  70 .....................    "p"
00000040:  7D .....................    "}"
00000041:  79 68 0A 04 00 0A 0F 00     "yh......"
00000049:  5E 5E 2E 44 53 50 43 42     "^^.DSPCB"
00000051:  52 54 43 ...............    "RTC"

      19:              ^^DSPC.BRTC = ((Arg0 << 0x04) | 0x0F)
00000054:  7D .....................    "}"
00000055:  79 68 0A 04 00 0A 0F 5E     "yh.....^"
0000005D:  5E 2E 44 53 50 43 42 52     "^.DSPCBR"
00000065:  54 43 ..................    "TC"

In the first statement, the "Store" instruction (0x70) is simply passed through to the .aml
In the second statement, the implied "Store" instruction (part of "^^DSPC.BRTC =" (the OR is opcode 0x7d) is optimized away, and the "Or" instruction does the "Store" as the third argument (the "target" operand).

Considering that the iASL compiler is essentially two compilers (Legacy ASL, and ASL v2), the Legacy ASL part of the compiler does not have the support to optimize the "Store" instruction away, but the ASL v2 compiler does have this support.

Thus, the resulting .aml files are different.

**Comment by ElyesH** [comment]
Thank you.
