### ISSUE TITLE
acpica.org is down 

### ISSUE THREAD

**Issue by ElyesH** [acpica/acpica#637]
we can't download the new release

Thx

**Comment by ElyesH** [comment]
Hi Erik,
Out of curiosity, was this a serious issue ?

**Comment by acpibob** [comment]
Yes, it certainly is a serious issue. We need to update the website with our latest release of our software.

**Comment by acpibob** [comment]
In other words, we cannot logon to the website (in order to update it).
Bob

**Comment by acpibob** [comment]
Web site is updated with ACPICA version 20200925.
