### ISSUE TITLE
source/components/dispatcher/dsfield.c: dead assignment

### ISSUE THREAD

**Issue by ElyesH** [acpica/acpica#641]
Hey,
At line 347, we have :  
"Status = AE_OK;"

but that "Status" is never used at all
moreover, we write on it at line 400 

(found by clang tool)

**Comment by ElyesH** [comment]
there is also  dead assignment here: 
- source/common/dmtbdump2.c line #2041 the value stored to "Status" is never read.
- source/compiler/dttable2.c line #1213 the value stored to "Status" is never read.

Dead increment: 
- source/common/dmtbdump2.c line #2062 Value stored to 'CurrentOffset' is never read.

(found using scabuild clang-tool)

**Comment by acpibob** [comment]
>At line 347, we have :

what's the module name?

**Comment by ElyesH** [comment]
going to  /dev/null
