### ISSUE TITLE
S3PT should not create a template

### ISSUE THREAD

**Issue by ahs3** [acpica/acpica#645]
If I run: "iasl -T s3pt" a template is produced.  The S3PT is a subtable of the FPDT in the ACPI spec so no template should be created.

**Comment by acpibob** [comment]
It's not really a subtable, but a separate table that is pointed to by the FPDT. And as such, it has it's own signature ("S3PT"), and it's own subtables (S3PT_TYPE_RESUME, S3PT_TYPE_SUSPEND, and FPDT Boot Performance Record.)

**Comment by acpibob** [comment]
And as such, a template for the S3PT is valid.

**Comment by acpibob** [comment]
Closing.
