### ISSUE TITLE
Undocumented tables: VRTC and MTMR

### ISSUE THREAD

**Issue by ahs3** [acpica/acpica#649]
In the process of converting code to support big-endian systems, I found two tables that are not defined in the ACPI spec and I cannot seem to find any formal definition for them:

- VRTC (Virtual Real Time Clock table)
- MTMT (MID Timer Table)

Just running 'iasl -T all' has produced some interesting results :).

I can create templates from them, and I can even support them big-endian.  But, I can not find any formal definition for these tables.  Have they been deprecated?  Should they be removed?  Or can we put a link to their definition in the spec?

**Comment by SchmErik** [comment]
@acpibob do you have documents for VRTC and MTMT in your archives?

**Comment by acpibob** [comment]
I don't think I have the documents.

**Comment by ahs3** [comment]
So these *were* defined at some point?  They're not in the spec at all.  Does anyone know who defined them so we can start some basic archaeology .... ?

**Comment by ahs3** [comment]
It looks like these tables were part of SFI (Simple Firmware Interface) which has since been deprecated and removed from the Linux kernel (5.6, specifically); please see wikipedia for more on SFI.  Len Brown of Intel is probably the original person involved.

Is there any reason to retain these, or should I just submit a patch removing them?  I thought maybe I had captured some examples in the wild but it was just the iASL templates.

**Comment by acpibob** [comment]
Sounds like you can submit a patch to remove these tables.
Bob
