### ISSUE TITLE
release artifact file name is malformed

### ISSUE THREAD

**Issue by chenrui333** [acpica/acpica#700]
👋  looks like the new release artifact is malformatted.
`https://acpica.org/sites/acpica/files/acpica-unix-20210604.tar_0.gz` rather than `https://acpica.org/sites/acpica/files/acpica-unix-20210604.tar.gz`

---

relates to Homebrew/homebrew-core#78750

**Comment by acpibob** [comment]
These are fixed.
Thanks,
Bob


From: rui ***@***.***>
Sent: Saturday, June 05, 2021 11:32 AM
To: acpica/acpica ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acpica/acpica] https link does not work for the latest release (#700)


👋 it looks like the latest release artifact is not downloadable using the https link.

- $ curl -I https://acpica.org/sites/acpica/files/acpica-unix-20210604.tar.gz



- HTTP/2 404



- server: nginx



+ $ curl -I http://acpica.org/sites/acpica/files/acpica-unix-20210604.tar.gz



+ HTTP/1.1 200 OK



+ Server: nginx

**Comment by chenrui333** [comment]
Thanks for the fix, I will wait a bit to see it shows up for me. Thanks!

**Comment by acpibob** [comment]
Fixed, Closing.

**Comment by chenrui333** [comment]
@acpibob 👋  I cannot see the right artifact, do you mind double checking on your end?

The release artifact is still `acpica-unix2-20210604.tar_0.gz` and `acpica-unix-20210604.tar.gz` still gives 404.

```
$ curl -I https://acpica.org/sites/acpica/files/acpica-unix2-20210604.tar_0.gz
HTTP/2 200
server: nginx
```

```
$ curl -I https://acpica.org/sites/acpica/files/acpica-unix-20210604.tar.gz
HTTP/2 404
server: nginx
```

**Comment by acpibob** [comment]
Yes, I don’t know how to get rid of the trailing “_0”.  This gets created if the first upload fails (which it did). Once it was fixed, the second upload gets the “_0”.
