### ISSUE TITLE
Tag named `HEAD`  should be removed as breaking tools like `west`

### ISSUE THREAD

**Issue by JohnVillalovos** [acpica/acpica#739]
I'm assuming that the tag named `HEAD` was created by mistake:
https://github.com/acpica/acpica/releases/tag/HEAD

This is breaking tools like `west` but also `HEAD` is used in git as a special name

https://git-scm.com/docs/gitglossary#def_HEAD

Can this tag be deleted?

**Comment by JohnVillalovos** [comment]
@acpibob Any ideas?

**Comment by shaba** [comment]
Delete tag HEAD, please.

**Comment by acpibob** [comment]
How do I go about deleting HEAD?

**Comment by JohnVillalovos** [comment]
https://devconnected.com/how-to-delete-local-and-remote-tags-on-git/

I haven't tried it but it says to do:

Delete a remote Git tag

In order to delete a remote Git tag, use the “git push” command with the “–delete” option and specify the tag name.

```
$ git push --delete origin tagname
```

You may want to test it on a dummy repository first.

Thanks!

**Comment by acpibob** [comment]
What is “origin” in the example git push?


$ git push --delete origin tagname

**Comment by JohnVillalovos** [comment]
> What is “origin” in the example git push?

`origin` is the remote name. By default when a `git clone` is done then `git` names the remote `origin`. But additional remotes can be added.

If you do `cat .git/config` from your project directory you can see your configuration. You can also do `git remote` or `git remote -v`

**Comment by acpibob** [comment]
When I do the git push –delete origin HOST, I get:

$ git push --delete origin HOST
error: unable to delete 'HOST': remote ref does not exist
error: failed to push some refs to ***@***.***/acpica/acpica.git'

**Comment by JohnVillalovos** [comment]
> When I do the git push –delete origin HOST, I get: $ git push --delete origin HOST error: unable to delete 'HOST': remote ref does not exist error: failed to push some refs to ***@***.***/acpica/acpica.git'

I think it should be `HEAD` not `HOST`

So:

```
git push –delete origin HEAD
```

**Comment by JohnVillalovos** [comment]
Oh and also should make sure that you don't have a local tag named `HEAD` so should also do:

```
git tag -d HEAD
```

Otherwise may end up pushing the `HEAD` tag again, if it exists.

**Comment by acpibob** [comment]
I end up with:

$ git tag -d HEAD
Deleted tag 'HEAD' (was 6774e67c6)

***@***.*** /cygdrive/c/acpica
$ git push --delete origin HOST
error: unable to delete 'HOST': remote ref does not exist
error: failed to push some refs to ***@***.***/acpica/acpica.git'

**Comment by JohnVillalovos** [comment]
> I end up with:
> $ git tag -d HEAD
> Deleted tag 'HEAD' (was 6774e67c6)

Great!

> ***@***.*** /cygdrive/c/acpica
> $ git push --delete origin HOST
> error: unable to delete 'HOST': remote ref does not exist error: failed to push some refs to ***@***.***/acpica/acpica.git'

Still using `HOST`. Should be `HEAD`

**Comment by JohnVillalovos** [comment]
As a note. I think you have done it because now when I go to: https://github.com/acpica/acpica/releases/tag/HEAD

I get a 404 page! 😊

**Comment by JohnVillalovos** [comment]
Thanks! I'm going to close this. I will test this tomorrow when I go to work but I feel very confident that the issue is resolved now.

Thanks again!

**Comment by JohnVillalovos** [comment]
>>As a note. I think you have done it because now when I go to: https://github.com/acpica/acpica/releases/tag/HEAD I get a 404 page! 😊 

>I take it this is a good thing

Yep! 😊
