### ISSUE TITLE
Add Second CEDT table (CFMWS).

### ISSUE THREAD

**Issue by MasterDrogo** [acpica/acpica#741]
The CEDT table is used for initializing the CXL ports.  While working on this, I found that only one of the sub-tables is being dumped properly.  I have added the code to disassemble and compile the CFMWS sub-table.
The issue is that the CFMWS is not dumped properly.  The last element is of variable length, so this will require a sub-sub table definition.
This is the table I am using:
[cedt_dump.txt](https://github.com/acpica/acpica/files/7830838/cedt_dump.txt)

**Comment by acpibob** [comment]
Please put in a pull request for this support.
Thanks,
Bob

**Comment by MasterDrogo** [comment]
This has been pulled and closed on January 27th.  Is there something else that I need to do?

**Comment by acpibob** [comment]
Closing.

**Comment by acpibob** [comment]
No, nothing else to do. I’ll close the issue.
