### ISSUE TITLE
iasl segfault when running "iasl *.dsl"

### ISSUE THREAD

**Issue by bcran** [acpica/acpica#749]
Ran the following on my Dell R7525 server.
```
acpidump > acpidump.out
acpixtract -a acpidump.out
iasl -d *.dat
iasl *.dsl
```
iasl causes a segmentation fault. It doesn't crash when the files are compiled one by one.
```
(gdb) run
Starting program: /home/bcran/acpi/acpica/generate/unix/bin/iasl apic.dsl bert.dsl cdit.dsl crat.dsl dsdt.dsl einj.dsl erst.dsl facp.dsl facs.dsl hest.dsl hpet.dsl ivrs.dsl mcfg.dsl msct.dsl pcct.dsl slit.dsl srat.dsl ssdt1.dsl ssdt2.dsl ssdt3.dsl ssdt4.dsl ssdt5.dsl ssdt6.dsl tpm2.dsl wsmt.dsl

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20211217
Copyright (c) 2000 - 2021 Intel Corporation


Program received signal SIGSEGV, Segmentation fault.
__strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
101     ../sysdeps/x86_64/multiarch/strcmp-avx2.S: No such file or directory.
(gdb) bt
#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
#1  0x000055555559792f in FlGetFileHandle ()
#2  0x0000555555595926 in AePrintErrorSourceLine ()
#3  0x0000555555595da2 in AePrintException ()
#4  0x0000555555595f2d in AePrintErrorLog ()
#5  0x0000555555594ce5 in CmCleanupAndExit ()
#6  0x000055555559eb67 in main ()
```

**Comment by acpibob** [comment]
Please post your acpidump.out file.
Thanks,
bob

**Comment by bcran** [comment]
[acpidump.out.zip](https://github.com/acpica/acpica/files/8044895/acpidump.out.zip)

**Comment by acpibob** [comment]
I think that I was able to reproduce the problem.

**Comment by acpibob** [comment]
Do you see a bunch of error messages like these?

ACPI Error: Result stack is empty! State=045DAF08 (20211217/dswstate-218)
ACPI Error: AE_AML_NO_RETURN_VALUE, Missing or null operand (20211217/dsutils-805)
ACPI Error: AE_AML_NO_RETURN_VALUE, While creating Arg 0 (20211217/dsutils-931)
ACPI Error: Needed type [Reference], found [Integer] 03FB7440 (20211217/exresop-222)
ACPI Error: AE_AML_OPERAND_TYPE, While resolving operands for [Mid] (20211217/dswexec-613)

**Comment by bcran** [comment]
No I don't get any error messages. The complete output is:
```
bcran@timp:~/acpi$ ./acpica/generate/unix/bin/iasl *.dsl

Intel ACPI Component Architecture
ASL+ Optimizing Compiler/Disassembler version 20211217
Copyright (c) 2000 - 2021 Intel Corporation

Segmentation fault
```

**Comment by acpibob** [comment]
I'm still looking at this when I can.

**Comment by acpibob** [comment]
Fix will be in the ACPICA release. Closing.
Bob
