### ISSUE TITLE
Issue [-Werror=format=]: source/common/dmtbdump2.c

### ISSUE THREAD

**Issue by selgan01** [acpica/acpica#761]
The ACPICA compilation halts due to the following format issue in the source/common/dmtbdump2.c. [Commit id: 4450b89b596a2b54b0cdfe2357b49a63445c2e03]. Please correct the errors.

../../../source/common/dmtbdump2.c: In function ‘AcpiDmDumpMadt’:
../../../source/common/dmtbdump2.c:890:70: error: format ‘%X’ expects argument of type ‘unsigned int’, but argument 4 has type ‘long int’ [-Werror=format=]
     DbgPrint (ASL_PARSE_OUTPUT, "//0B) Offset %X, from table start: %X\n",
                                                                     ~^
                                                                     %lX
../../../source/common/dmtbdump2.c:1008:79: error: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long int’ [-Werror=format=]
                 DbgPrint (ASL_PARSE_OUTPUT, "//[0A) Offset from table start: %X]\n",
                                                                              ~^
                                                                              %lX
../../../source/common/dmtbdump2.c:1050:70: error: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long int’ [-Werror=format=]
         DbgPrint (ASL_PARSE_OUTPUT, "//[4) Offset from table start: %X (%p) %p]\n",
                                                                     ~^
                                                                     %lX
../../../source/common/dmtbdump2.c:1062:71: error: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long int’ [-Werror=format=]
         DbgPrint (ASL_PARSE_OUTPUT, "//[5B) Offset from table start: %X %p]\n",
                                                                      ~^
                                                                      %lX

**Comment by acpibob** [comment]
Fixed for the next release of ACPICA.
Closing.
