### ISSUE TITLE
[Question] Secure Devices (SDEV) ACPI Table.

### ISSUE THREAD

**Issue by 4xljp** [acpica/acpica#769]
Hi,

I have some problems when project need adapt SSDT ACPI table,
is SDEV Table uniqueness?
or system may have one or more SDEV table just like SSDT table?

Current chipset vendor (Intel) create their own SDEV table in chipset reference code,
and third party devices want create SDEV table also,
does project should append SDEV structure data after existed SDEV raw buffer ?
or project can create new SDEV table for third party devices extra ?

Thank you very much.

**Comment by 4xljp** [comment]
Hi,

Thank for reply,

Because specific data of device of SDEV Table doesn't define in common rule,
chipset vendor may have their own SDEV table.

So,
if i have following items :
1. AMD/Intel Chipset original SDEV table.
2. third party pci xhc / pci SPI / pci I2C.
3. cam
4. finger printer.

For xhc & Pci I2C / SPI Hc,
Then new SDEV table structure will be 
original SDEV table RawData + \
SDEV PCIe EndPoint Struct (3rd party xhc)+ Specific Data 1 (3rd party xhc) + \
ACPI_NAMESPACE_DEVICE (Cam) + Specific data2 (Cam) + \
ACPI_NAMESPACE_DEVICE (finger printer) + Specific data3 (finger printer) 

or
for Embedded MMIO I2C / SPI Host Controller
original SDEV table RawData + \
SDEV memory-base structure + Specific Data 1 (I2C / SPI) + \
ACPI_NAMESPACE_DEVICE (3rd party Cam) + Specific data2 (3rd party Cam) + \
ACPI_NAMESPACE_DEVICE (3rd party finger printer) + Specific data3 (3rd party finger printer) 

Right ?

Thank you very much.

**Comment by acpibob** [comment]
Yes, I suppose this should work. Although I have never seen an ACPI table modified like this.
Bob

**Comment by 4xljp** [comment]
Thank you so much.
