### ISSUE TITLE
Pls fix typo in /source/include/actbl2.h line 1533

### ISSUE THREAD

**Issue by OS4User** [acpica/acpica#783]
OemData[0];  ->  OemData[];

**Comment by acpibob** [comment]
Can you make this into a pull request on gitub?
Thanks,
Bob


From: OS4User ***@***.***>
Sent: Monday, June 20, 2022 10:42 PM
To: acpica/acpica ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acpica/acpica] Pls fix typo in /source/include/actbl2.h line 1533 (Issue #783)


OemData[0]; -> OemData[];

**Comment by OS4User** [comment]
I'm not working with Git, so creating a pull request will be a bit difficult.
If you don't mind, just delete this '0' yourself.
Regards,
Alex
