### ISSUE TITLE
acphelp -v segmentation fault

### ISSUE THREAD

**Issue by sbockowx** [acpica/acpica#785]
Hi,
when I use acpihelp -v on SLES 15 SP2 or Centos 8 Stream I received:
acpihelp -v

Intel ACPI Component Architecture
ACPI Help Utility version 20220331
Copyright (c) 2000 - 2022 Intel Corporation

Segmentation fault (core dumped)

**Comment by acpibob** [comment]
Fixed in ACPICA version 20221020, closing
