### ISSUE TITLE
Two ACPI_TABLE_CEDT entries appear in AcpiIdentifiers[] 

### ISSUE THREAD

**Issue by dnlsn** [acpica/acpica#791]
Two occurrences of '{"ACPI_TABLE_CEDT", SRC_TYPE_STRUCT}' appear in AcpiIdentifiers[], as found in source/tools/acpisrc/astable.c.

The 1st occurrence was added by 0b03aa8ebd7a ("CXL 2.0: CEDT: Add new CEDT table"), via this hunk...
```
  diff --git a/source/tools/acpisrc/astable.c b/source/tools/acpisrc/astable.c
  index f7906b5c0..010ef884a 100644
  --- a/source/tools/acpisrc/astable.c
  +++ b/source/tools/acpisrc/astable.c
  @@ -641,6 +641,7 @@ ACPI_TYPED_IDENTIFIER_TABLE           AcpiIdentifiers[] = {
       {"ACPI_TABLE_BERT",                     SRC_TYPE_STRUCT},
       {"ACPI_TABLE_BGRT",                     SRC_TYPE_STRUCT},
       {"ACPI_TABLE_BOOT",                     SRC_TYPE_STRUCT},
  +    {"ACPI_TABLE_CEDT",                     SRC_TYPE_STRUCT},
       {"ACPI_TABLE_CPEP",                     SRC_TYPE_STRUCT},
       {"ACPI_TABLE_CSRT",                     SRC_TYPE_STRUCT},
       {"ACPI_TABLE_DBG2",                     SRC_TYPE_STRUCT},
```
And the 2nd occurrence was added by 1e6dded267b1 ("iASL/TableCompiler: Add compilation support for CEDT table"), via this hunk...
```
  diff --git a/source/tools/acpisrc/astable.c b/source/tools/acpisrc/astable.c
  index 37679be1b..3438f13af 100644
  --- a/source/tools/acpisrc/astable.c
  +++ b/source/tools/acpisrc/astable.c
  @@ -648,6 +648,7 @@ ACPI_TYPED_IDENTIFIER_TABLE           AcpiIdentifiers[] = {
       {"ACPI_TABLE_CSRT",                     SRC_TYPE_STRUCT},
       {"ACPI_TABLE_DBG2",                     SRC_TYPE_STRUCT},
       {"ACPI_TABLE_DBGP",                     SRC_TYPE_STRUCT},
  +    {"ACPI_TABLE_CEDT",                     SRC_TYPE_STRUCT},
       {"ACPI_TABLE_DMAR",                     SRC_TYPE_STRUCT},
       {"ACPI_TABLE_DRTM",                     SRC_TYPE_STRUCT},
       {"ACPI_TABLE_ECDT",                     SRC_TYPE_STRUCT},
```
This 2nd occurrence should be removed, as follows...
```
diff --git a/source/tools/acpisrc/astable.c b/source/tools/acpisrc/astable.c
index 0d76926a5..2ff235384 100644
--- a/source/tools/acpisrc/astable.c
+++ b/source/tools/acpisrc/astable.c
@@ -654,7 +654,6 @@ ACPI_TYPED_IDENTIFIER_TABLE           AcpiIdentifiers[] = {
     {"ACPI_TABLE_CSRT",                     SRC_TYPE_STRUCT},
     {"ACPI_TABLE_DBG2",                     SRC_TYPE_STRUCT},
     {"ACPI_TABLE_DBGP",                     SRC_TYPE_STRUCT},
-    {"ACPI_TABLE_CEDT",                     SRC_TYPE_STRUCT},
     {"ACPI_TABLE_DMAR",                     SRC_TYPE_STRUCT},
     {"ACPI_TABLE_DRTM",                     SRC_TYPE_STRUCT},
     {"ACPI_TABLE_ECDT",                     SRC_TYPE_STRUCT},
```

**Comment by acpibob** [comment]
OK, done.
Thanks,
Bob


From: dnlsn ***@***.***>
Sent: Friday, August 26, 2022 11:49 AM
To: acpica/acpica ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acpica/acpica] Two ACPI_TABLE_CEDT entries appear in AcpiIdentifiers[] (Issue #791)


Two occurrences of '{"ACPI_TABLE_CEDT", SRC_TYPE_STRUCT}' appear in AcpiIdentifiers[], as found in source/tools/acpisrc/astable.c.

The 1st occurrence was added by 0b03aa8<https://github.com/acpica/acpica/commit/0b03aa8ebd7a5b2b9407893f123ee587af45926f> ("CXL 2.0: CEDT: Add new CEDT table"), via this hunk...

  diff --git a/source/tools/acpisrc/astable.c b/source/tools/acpisrc/astable.c

  index f7906b5c0..010ef884a 100644

  --- a/source/tools/acpisrc/astable.c

  +++ b/source/tools/acpisrc/astable.c

  @@ -641,6 +641,7 @@ ACPI_TYPED_IDENTIFIER_TABLE           AcpiIdentifiers[] = {

       {"ACPI_TABLE_BERT",                     SRC_TYPE_STRUCT},

       {"ACPI_TABLE_BGRT",                     SRC_TYPE_STRUCT},

       {"ACPI_TABLE_BOOT",                     SRC_TYPE_STRUCT},

  +    {"ACPI_TABLE_CEDT",                     SRC_TYPE_STRUCT},

       {"ACPI_TABLE_CPEP",                     SRC_TYPE_STRUCT},

       {"ACPI_TABLE_CSRT",                     SRC_TYPE_STRUCT},

       {"ACPI_TABLE_DBG2",                     SRC_TYPE_STRUCT},

And the 2nd occurrence was added by 1e6dded<https://github.com/acpica/acpica/commit/1e6dded267b13c4aa0c3e16de0fa89d3b9c880e9> ("iASL/TableCompiler: Add compilation support for CEDT table"), via this hunk...

  diff --git a/source/tools/acpisrc/astable.c b/source/tools/acpisrc/astable.c

  index 37679be1b..3438f13af 100644

  --- a/source/tools/acpisrc/astable.c

  +++ b/source/tools/acpisrc/astable.c

  @@ -648,6 +648,7 @@ ACPI_TYPED_IDENTIFIER_TABLE           AcpiIdentifiers[] = {

       {"ACPI_TABLE_CSRT",                     SRC_TYPE_STRUCT},

       {"ACPI_TABLE_DBG2",                     SRC_TYPE_STRUCT},

       {"ACPI_TABLE_DBGP",                     SRC_TYPE_STRUCT},

  +    {"ACPI_TABLE_CEDT",                     SRC_TYPE_STRUCT},

       {"ACPI_TABLE_DMAR",                     SRC_TYPE_STRUCT},

       {"ACPI_TABLE_DRTM",                     SRC_TYPE_STRUCT},

       {"ACPI_TABLE_ECDT",                     SRC_TYPE_STRUCT},

This 2nd occurrence should be removed, as follows...

diff --git a/source/tools/acpisrc/astable.c b/source/tools/acpisrc/astable.c

index 0d76926a5..2ff235384 100644

--- a/source/tools/acpisrc/astable.c

+++ b/source/tools/acpisrc/astable.c

@@ -654,7 +654,6 @@ ACPI_TYPED_IDENTIFIER_TABLE           AcpiIdentifiers[] = {

     {"ACPI_TABLE_CSRT",                     SRC_TYPE_STRUCT},

     {"ACPI_TABLE_DBG2",                     SRC_TYPE_STRUCT},

     {"ACPI_TABLE_DBGP",                     SRC_TYPE_STRUCT},

-    {"ACPI_TABLE_CEDT",                     SRC_TYPE_STRUCT},

     {"ACPI_TABLE_DMAR",                     SRC_TYPE_STRUCT},

     {"ACPI_TABLE_DRTM",                     SRC_TYPE_STRUCT},

     {"ACPI_TABLE_ECDT",                     SRC_TYPE_STRUCT},

**Comment by acpibob** [comment]
Fixed, closing.
