### ISSUE TITLE
Hi there, is this available in linux kernel and can I use this to read DSDT table in kernel programming?

### ISSUE THREAD

**Issue by DK-DARKmatter** [acpica/acpica#796]
I'm learning about linux kernel programming. As part of my study I am trying to read DSDT information and print them out.
There's no very easy-understanding way to achieve that, and I am wondering if acpica is available in linux kernel and I could use any of the API to do this.

Thanks in advance

**Comment by superm1** [comment]
In your Linux distribution you can install acpica-utils and then you can access the DSDT from `/sys/firmware/acpi/tables/DSDT` and use the tool `iasl` to decompile it.
