### ISSUE TITLE
Guidelines to add new ACPI table

### ISSUE THREAD

**Issue by vlsunil** [acpica/acpica#797]
What are the guidelines to add a new table definition in ACPICA? https://github.com/acpica/acpica/blob/master/source/compiler/new_table.txt says that actbl3.h should be used for any table defined in the ACPI spec. But many tables which are in the spec are actually seen in actbl2.h. And some tables are added actbl1.h . 

Could someone please help with guidelines when to use actbl1/actbl2/actbl3?

**Comment by acpibob** [comment]
Actbl1 started out as being for the tables consumed directly by ACPICA, but this became corrupted over time.

Actbl2 and Actbl3 are basically for the remaining tables, in alphabetical order, but even this has been corrupted over time. So, the smallest .h file should be for new tables. Actbl2 was for tables defined in the ACPI spec, and actbl3 was for tables not defined in the ACPI spec.

Bob


From: vlsunil ***@***.***>
Sent: Friday, September 23, 2022 5:06 AM
To: acpica/acpica ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [acpica/acpica] Guidle lines to add new ACPI table (Issue #797)


What are the guidelines to add a new table definition in ACPICA? https://github.com/acpica/acpica/blob/master/source/compiler/new_table.txt says that actbl3.h should be used for any table defined in the ACPI spec. But many tables which are in the spec are actually seen in actbl2.h. And some tables are added actbl1.h .

Could someone please help with guidelines when to use actbl1/actbl2/actbl3?

**Comment by vlsunil** [comment]
Thank you very much! Bob. This is helpful.
