### ISSUE TITLE
Are illegal port ranges still valid?

### ISSUE THREAD

**Issue by superm1** [acpica/acpica#816]
Hi,

I've come across an issue where SBIOS is attempting to write 4 bytes to port I/O 0x80 from AML, and this fails.  Only the first byte is written, and with the Linux kernel debug logs turned up to indicate why the following messages come up:

```
[1058741.307688]   hwvalid-0149 hw_validate_io_request: Denied AML access to port 0x0000000000000080/4 (DMA1 0x0081-0x0083)
[1058741.307694]   hwvalid-0149 hw_validate_io_request: Denied AML access to port 0x0000000000000081/1 (DMA1 0x0081-0x0083)
[1058741.307695]   hwvalid-0149 hw_validate_io_request: Denied AML access to port 0x0000000000000082/1 (DMA1 0x0081-0x0083)
[1058741.307696]   hwvalid-0149 hw_validate_io_request: Denied AML access to port 0x0000000000000083/1 (DMA1 0x0081-0x0083)
```

So the kernel tries to do a 4 byte write, then that's rejected so they're done 1 byte at a time.  Only the first byte succeeds.

I was looking more into this, and it seems that it was introduced because Windows had protected port I/O ranges introduced during the Windows XP timeframe.  If the BIOS tried to write to those ranges messages like this would show up in the Windows event viewer (found from a random search):

```
Source: ACPI
Category: None
Type: Error
Event ID: 5
User: N/A
Computer: Machine_Name
Description: AMLI: ACPI BIOS is attempting to write to an illegal IO port address (0xcf8),
             which lies in the 0xcf8 - 0xcff protected address range. This could lead
             to system instability. Please contact your system vendor for technical assistance. 
             For more information, see Help and Support Center at: 
             http://go.microsoft.com/fwlink/events.asp
```

However taking this exact same system over to Windows 11 and trying to execute the same AML no such messages are emitted and checking the other end of the port I/O all 4 bytes were written.

So I wanted to check; is it really still valid to be guarding the port I/O writes for the DMA1 range?  I'm not sure where the original ranges from https://github.com/acpica/acpica/blob/44ab01315dc9b431df6ede6504f9261f706c62ed/source/components/hardware/hwvalid.c#L205 came from, but at least I couldn't find anything similar searching the public Microsoft website myself.

1. Can these ranges checks be loosened on the more modern OSI values?
2. Or perhaps drop the DMA1 range to help this issue I'm reporting?

**Comment by superm1** [comment]
I think these are the original URLs:
* http://www.microsoft.com/hwdev/tech/onnow/BIOSAML.asp 
* http://support.microsoft.com/default.aspx?scid=kb;en-us;Q283649 
* http://www.microsoft.com/whdc/system/pnppwr/powermgmt/BIOSAML.mspx

But all are long dead.  All the mentions I'm finding on the internet for this error are 15+ years old, and given I don't personally see errors in Windows but this wrong behavior in Linux I'm suspecting that Windows doesn't really check it anymore.

So I'm in favor of just tearing out all the protected ranges support to fix this issue.  But if you think they still make sense generally another way to do it is to only check them if running on an OSI older than some point (first Windows 10 release?).

**Comment by acpibob** [comment]
I would vote to take them out if they are all obsolete.
