### ISSUE TITLE
Handling of Integers in ToHexString() problematic

### ISSUE THREAD

**Issue by Wer-Wolf** [acpica/acpica#827]
Sadly, the ACPI specification does only vaguely define the format of the string produced by ToHexString().
As for the handling of integers with ToHexString(), i observed that the ACPI implementation of Microsoft Windows does implement ToHexString() differently than ACPICA:

Windows:
byte 0x0f =>"0xf"
word 0x0f0f => "0xf0f"
dword 0x0f0f0f0f => "0xf0f0f0f"
qword 0x0f0f0f0f0f0f0f0f => "0xf0f0f0f0f0f0f0f"

ACPICA:
byte 0x0f =>"0000000f"
word 0x0f0f => "00000f0f"
dword 0x0f0f0f0f => "0f0f0f0f"
qword 0x0f0f0f0f0f0f0f0f => "0f0f0f0f" (32-bit table, but qword is 64-bit?)

This causes problems on my Inspiron 3505, as the battery serial number generated by using ToHexString(<16 bit field>, Local1) and Mid(Local1, 0x02, 0x04, Local0), causing a wrong serial number to be displayed.

I already wrote a email to the ASWG suggesting clarifying the string format of ToHexString() in a future revision of the ACPI standard,
but i am still waiting for a reply.

Could the behavior of ToHexString() for integers be changed to match the Windows behavior? Something similar was already done in version 20181213.

**Comment by sacdintel** [comment]
When your PR 903 merges, does it resolve this issue 827? Thanks.

**Comment by Wer-Wolf** [comment]
Yes

**Comment by sacdintel** [comment]
Completed via PR 903 merge.
