### ISSUE TITLE
DtCompileString may buffer-overflow

### ISSUE THREAD

**Issue by andree182** [acpica/acpica#930]
With -Werror=format-overflow and _FORTIFY_SOURCE the compilation fails with:

```
../../../source/compiler/dtfield.c:` In function 'DtCompileOneField':
../../../source/compiler/dtfield.c:176:58: warning: '%s' directive writing between 1 and 2147483645 bytes into a region of size between 131012 and 131030 [-Wformat-overflow=]
  176 |             "Maximum %u characters, found %u characters [%s]",
      |                                                          ^~
In file included from /opt/elinos-7.2/cdk/x86/i686/glibc/i686-unknown-linux-gnu/include/stdio.h:906,
                 from ../../../source/include/platform/acenv.h:389,
                 from ../../../source/include/acpi.h:56,
                 from ../../../source/compiler/aslcompiler.h:47,
                 from ../../../source/compiler/dtfield.c:44:
In function 'sprintf',
    inlined from 'DtCompileString' at ../../../source/compiler/dtfield.c:175:9,
    inlined from 'DtCompileOneField' at ../../../source/compiler/dtfield.c:111:9:
/opt/elinos-7.2/cdk/x86/i686/glibc/i686-unknown-linux-gnu/include/bits/stdio2.h:30:10: note: '__builtin___sprintf_chk' output between 45 and 2147483707 bytes into a destination of size 131072
   30 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   31 |                                   __glibc_objsize (__s), __fmt,
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   32 |                                   __va_arg_pack ());
      |                                   ~~~~~~~~~~~~~~~~~
```

Patch like this helps:

```
--- acpica-unix-20200925/source/compiler/dtfield.c.orig	2024-02-20 09:46:31.218357110 +0100
+++ acpica-unix-20200925/source/compiler/dtfield.c	2024-02-20 09:58:25.056203086 +0100
@@ -173,7 +173,7 @@ DtCompileString (
     if (Length > ByteLength)
     {
         sprintf (AslGbl_MsgBuffer,
-            "Maximum %u characters, found %u characters [%s]",
+            "Maximum %u characters, found %u characters [%.4096s]",
             ByteLength, Length, Field->Value);
         DtError (ASL_ERROR, ASL_MSG_STRING_LENGTH, Field, AslGbl_MsgBuffer);
         Length = ByteLength;

```

but probably instead something like `...%.*s", ... sizeof(ASL_MSG_BUFFER_SIZE)/2, Field->Value);` would be better.

**Comment by sacdintel** [comment]
https://github.com/acpica/acpica/commit/0e9cfe0a6e48c98233b93df46e5879909c118f8f

Hi @andree182 ,

I have posted a commit as above to address this issue. I simply took your suggestions and added another argument to sprintf() and made sure to have the string format bounded. Kindly give it a look and let me know if it looks good to you, so that I can go ahead and mark this issue as 'close as complete'. Thanks a lot for reporting this issue!

**Comment by andree182** [comment]
This is not correct, because

#define ASL_MSG_BUFFER_SIZE             (1024 * 128) /* 128k */
ASL_EXTERN char                     AslGbl_MsgBuffer[ASL_MSG_BUFFER_SIZE];

so you need something like (ASL_MSG_STRING_LENGTH-sizeof("Maximum %u characters, found %u characters [%.*s]")) as maximum, +-1 :-)

I'd say - just limit it to 256 or whatever, that should be enough context for anyone in such a debug message...

**Comment by sacdintel** [comment]
OK I think I know what you meant and this commit

https://github.com/acpica/acpica/commit/9a3a339508c21d8a4e659a5fece79c60a83f020c

 will hopefully fix the issue finally. Please take a look and let me know, thanks!

**Comment by andree182** [comment]
Sorry, I made a copy-paste mistake above - ASL_MSG_STRING_LENGTH is some enum? It should be ASL_MSG_BUFFER_SIZE, but no idea where the '-2' came from (in your commit), you need to account for all the %... things in the string. I wouldn't want to maintain that code... :)

I suggest to just use ASL_MSG_BUFFER_SIZE / 2 and close this.

**Comment by sacdintel** [comment]
Thanks for the simplification, I made a commit like you asked here 

https://github.com/acpica/acpica/commit/6eb3afee0d70ef35e023026c753b43fdc1cf6d7b

and now I can close this issue!
