### ISSUE TITLE
Whatever happened to GPE block devices?

### ISSUE THREAD

**Issue by d-tatianin** [acpica/acpica#932]
This might be a wrong place to ask but:
- In 2003 ACPICA added support for GPE block devices: https://github.com/acpica/acpica/commit/e257e4f15a425c78fe8c50fa964c93f4b44ee69e
- Linux patch to support them was sent 20! years later: [here](https://patchwork.kernel.org/project/linux-acpi/patch/20231002084045.475843-1-michal.wilczynski@intel.com/)
- Looking at dumps of about 500 different AML blobs [here](https://github.com/linuxhw/ACPI):
```
❯ grep -rn 'ACPI0006' ./ --exclude \*.bin | wc -l
0
```

It seems to introduce quite a bit of extra complexity to the GPE code for no reason.

Is this feature abandoned? How come has nobody ever used it? Is it worth supporting in 2024?

Thanks!

**Comment by Wer-Wolf** [comment]
I do not thing that the feature is abandoned, it just that most system are perfectly fine with only using the two GPEs inside the FADT.

Also it seems that Windows [does not support it](https://git.mirrors.cqupt.edu.cn/QEMU/QEMU/commit/d31c909e57a131dec7a1e620f36573f2f5fca9e5), so most consumer hardware will not use it.

**Comment by sacdintel** [comment]
Adding @rafaeljw for some historic context and the future plans in Linux which I lack! Thanks a lot!

**Comment by rafaeljw** [comment]
As far as things stand today, the GPE block device definition is still there in the ACPI specification, but no platforms shipped so far (as far as I can say) have used it.

Linux does not enumerate GPE block devices as of today and currently there are no plans (that I am aware of) to add support for enumerating GPE block devices to Linux.

**Comment by d-tatianin** [comment]
I see, thank you!

**Comment by sacdintel** [comment]
Thanks a lot @rafaeljw and @d-tatianin for the conversation and for helping resolve this issue!
