### ISSUE TITLE
Linux upstream vs ACPICA divergence for the GPE subsystem

### ISSUE THREAD

**Issue by d-tatianin** [acpica/acpica#935]
Linux upstream has the following patch applied since March 2020: https://github.com/torvalds/linux/commit/0ce792d660bda990c675eaf14ce09594a9b85cbf

Looks like ACPICA upstream just got one of the earlier patches (February 2020):
https://github.com/acpica/acpica/commit/6d63ef81615e22ef5622ff3d9161352e146cf78b

Is this divergence expected/intended, or was that piece forgotten?

**Comment by Wer-Wolf** [comment]
It seems that the linux patch was for a linux-specific feature (to ignore some GPEs when calling acpi_any_gpe_status_set()), so maybe that the reason why it was not submitted to ACPICA.

The patch author might have the answer to your question.

**Comment by sacdintel** [comment]
Eric no longer works as the ACPICA maintainer and I am essentially his replacement, but maybe @rafaeljw can have something to say about this divergence?

**Comment by rafaeljw** [comment]
The patch in question is mine and it is indeed a Linux-specific feature and the divergence is expected.

**Comment by d-tatianin** [comment]
> The patch in question is mine and it is indeed a Linux-specific feature and the divergence is expected.

Thank you! What went into the decision to keep it linux-only?

**Comment by rafaeljw** [comment]
It is used specifically for addressing a very specific problem related to a Linux-specific feature (suspend-to-idle) that is unlikely to be present in any other OS that does not implement the same feature in more-or-less the same way.

**Comment by d-tatianin** [comment]
Makes sense, thanks!

**Comment by sacdintel** [comment]
Thanks a lot to you both Rafael and Daniil for this discussion and also helping resolve this issue!
