### ISSUE TITLE
Git tag names

### ISSUE THREAD

**Issue by felixsinger** [acpica/acpica#969]
The tag names did vary a lot in the past releases. Please be consistent with that, since package maintainers are using these.

**Comment by sacdintel** [comment]
Sorry about that, I realized that when doing this latest release and unfortunately even commits from the release before that have been tagged with the latest release. I will try to be uniform with tagging and maybe getting rid of the GYYYYMMDD format for the GitHub releases might be the best thing and in the future they can all have the same consistent Rmm_dd_yyyy format? Let me know your suggestions please, thanks!

**Comment by paulmenzel** [comment]
I also noticed this. *Rmm_dd_yyyy* has the downside of not being sortable.

**Comment by SaketADumbre** [comment]
I am open to suggestions on what the best option for the tag name formatting should be. How about something like Ryyyy_mm_dd format which can solve the chronological sorting problem and we don't stray too far away from the historical format of Rmm_dd_yyyy as well?

**Comment by paulmenzel** [comment]
Sounds good to me.

**Comment by SaketADumbre** [comment]
Thanks for the feedback @paulmenzel and for this upcoming release I will experiment with this new format and gauge the community reaction to that.

**Comment by felixsinger** [comment]
Sorry for my silence. Ryyyy_mm_dd looks good to me. Thank you for taking care :)

**Comment by felixsinger** [comment]
I think we can close this issue then. Thank you again!
