### ISSUE TITLE
[regression] `Table [SSDT] was not found in …`

### ISSUE THREAD

**Issue by paulmenzel** [acpica/acpica#978]
Since commit https://github.com/acpica/acpica/commit/ad5755dd80718b02d797b184ba290789ea89f274, `acpidump` is unable to extract the SSDT of my [ACPI table dump](https://github.com/user-attachments/files/17434061/dump.txt).

    ad5755dd80718b02d797b184ba290789ea89f274 is the first bad commit
    commit ad5755dd80718b02d797b184ba290789ea89f274
    Author: Daniil Tatianin <99danilt@gmail.com>
    Date:   Sun Jul 7 23:46:46 2024 +0300

        acpixtract: don't abort AxExtractTables for AX_OPTIONAL_TABLES
    
        Otherwise this makes the utility return an error for invocations like
        "acpixtract <FILE>", where FILE contains a DSDT but no SSDTs.
    
        Signed-off-by: Daniil Tatianin <99danilt@gmail.com>

     source/tools/acpixtract/acpixtract.c | 2 +-
     1 file changed, 1 insertion(+), 1 deletion(-)

Reverting the commit on top of the master branch (tag R09_27_24) also fixes my issue.

\cc @d-tatianin, @sacdintel

PS: This is a common dump from an Intel Kaby Lake Dell XPS 13 9360. Any idea, how nobody else hit this issue? Is there a test suite?

**Comment by d-tatianin** [comment]
Oops, I think that's a logic bug. The condition should be something like this
```diff
-        if (Instances < MinimumInstances || MinimumInstances == AX_OPTIONAL_TABLES)
+        if (Instances < MinimumInstances || (Instances == 0 && MinimumInstances == AX_OPTIONAL_TABLES))
```

I'll submit a fix

**Comment by paulmenzel** [comment]
> Oops, I think that's a logic bug. The condition should be something like this
> 
> ```diff
> -        if (Instances < MinimumInstances || MinimumInstances == AX_OPTIONAL_TABLES)
> +        if (Instances < MinimumInstances || (Instances == 0 && MinimumInstances == AX_OPTIONAL_TABLES))
> ```

That fixes it for me.

> I'll submit a fix

Awesome.
